#ifndef PLQ_VERIFIER_H
#define PLQ_VERIFIER_H

/* Generated by flatcc 0.6.1 FlatBuffers schema compiler for C by dvide.com */

#ifndef PLQ_READER_H
#include "plq_reader.h"
#endif
#include "flatcc/flatcc_verifier.h"
#include "flatcc/flatcc_prologue.h"

static int PLQ_plq_frame_t_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PLQ_plq_mapchange_t_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PLQ_plq_lightstyle_t_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PLQ_plq_lightstyles_t_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PLQ_plq_disconnect_t_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PLQ_plq_input_t_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PLQ_plq_command_t_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PLQ_plq_resourcereq_t_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PLQ_plq_resourceresp_t_verify_table(flatcc_table_verifier_descriptor_t *td);
static int PLQ_plq_message_t_verify_table(flatcc_table_verifier_descriptor_t *td);

static int PLQ_plq_payload_t_union_verifier(flatcc_union_verifier_descriptor_t *ud)
{
    switch (ud->type) {
    case 1: return flatcc_verify_union_table(ud, PLQ_plq_frame_t_verify_table); /* plq_frame_t */
    case 2: return flatcc_verify_union_table(ud, PLQ_plq_mapchange_t_verify_table); /* plq_mapchange_t */
    case 3: return flatcc_verify_union_table(ud, PLQ_plq_lightstyles_t_verify_table); /* plq_lightstyles_t */
    case 4: return flatcc_verify_union_table(ud, PLQ_plq_disconnect_t_verify_table); /* plq_disconnect_t */
    case 5: return flatcc_verify_union_table(ud, PLQ_plq_input_t_verify_table); /* plq_input_t */
    case 6: return flatcc_verify_union_table(ud, PLQ_plq_command_t_verify_table); /* plq_command_t */
    case 7: return flatcc_verify_union_table(ud, PLQ_plq_resourcereq_t_verify_table); /* plq_resourcereq_t */
    case 8: return flatcc_verify_union_table(ud, PLQ_plq_resourceresp_t_verify_table); /* plq_resourceresp_t */
    default: return flatcc_verify_ok;
    }
}

static inline int PLQ_usercmd_t_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, PLQ_usercmd_t_identifier, 24, 4);
}

static inline int PLQ_usercmd_t_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, PLQ_usercmd_t_type_hash, 24, 4);
}

static inline int PLQ_usercmd_t_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 24, 4);
}

static inline int PLQ_usercmd_t_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 24, 4);
}

static inline int PLQ_entity_state_t_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, PLQ_entity_state_t_identifier, 36, 4);
}

static inline int PLQ_entity_state_t_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, PLQ_entity_state_t_type_hash, 36, 4);
}

static inline int PLQ_entity_state_t_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 36, 4);
}

static inline int PLQ_entity_state_t_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 36, 4);
}

static inline int PLQ_dlight_t_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, PLQ_dlight_t_identifier, 48, 4);
}

static inline int PLQ_dlight_t_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, PLQ_dlight_t_type_hash, 48, 4);
}

static inline int PLQ_dlight_t_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 48, 4);
}

static inline int PLQ_dlight_t_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 48, 4);
}

static inline int PLQ_cshift_t_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, PLQ_cshift_t_identifier, 16, 4);
}

static inline int PLQ_cshift_t_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, PLQ_cshift_t_type_hash, 16, 4);
}

static inline int PLQ_cshift_t_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 16, 4);
}

static inline int PLQ_cshift_t_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 16, 4);
}

static inline int PLQ_plq_viewstate_t_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, PLQ_plq_viewstate_t_identifier, 56, 8);
}

static inline int PLQ_plq_viewstate_t_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, PLQ_plq_viewstate_t_type_hash, 56, 8);
}

static inline int PLQ_plq_viewstate_t_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 56, 8);
}

static inline int PLQ_plq_viewstate_t_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 56, 8);
}

static inline int PLQ_plq_stats_t_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, PLQ_plq_stats_t_identifier, 64, 4);
}

static inline int PLQ_plq_stats_t_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, PLQ_plq_stats_t_type_hash, 64, 4);
}

static inline int PLQ_plq_stats_t_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_struct_as_typed_root(buf, bufsiz, thash, 64, 4);
}

static inline int PLQ_plq_stats_t_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_struct_as_root(buf, bufsiz, fid, 64, 4);
}

static int PLQ_plq_frame_t_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 56, 8) /* view */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 64, 4) /* stats */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 2, 0, 36, 4, INT64_C(119304647)) /* entities */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 3, 0, 48, 4, INT64_C(89478485)) /* dlights */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 4, 0, 16, 4, INT64_C(268435455)) /* cshifts */)) return ret;
    return flatcc_verify_ok;
}

static inline int PLQ_plq_frame_t_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PLQ_plq_frame_t_identifier, &PLQ_plq_frame_t_verify_table);
}

static inline int PLQ_plq_frame_t_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PLQ_plq_frame_t_type_identifier, &PLQ_plq_frame_t_verify_table);
}

static inline int PLQ_plq_frame_t_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PLQ_plq_frame_t_verify_table);
}

static inline int PLQ_plq_frame_t_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PLQ_plq_frame_t_verify_table);
}

static int PLQ_plq_mapchange_t_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* mapname */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* levelname */)) return ret;
    if ((ret = flatcc_verify_field(td, 2, 1, 1) /* maxclients */)) return ret;
    if ((ret = flatcc_verify_field(td, 3, 1, 1) /* gametype */)) return ret;
    return flatcc_verify_ok;
}

static inline int PLQ_plq_mapchange_t_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PLQ_plq_mapchange_t_identifier, &PLQ_plq_mapchange_t_verify_table);
}

static inline int PLQ_plq_mapchange_t_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PLQ_plq_mapchange_t_type_identifier, &PLQ_plq_mapchange_t_verify_table);
}

static inline int PLQ_plq_mapchange_t_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PLQ_plq_mapchange_t_verify_table);
}

static inline int PLQ_plq_mapchange_t_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PLQ_plq_mapchange_t_verify_table);
}

static int PLQ_plq_lightstyle_t_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* index */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 1, 0) /* map */)) return ret;
    return flatcc_verify_ok;
}

static inline int PLQ_plq_lightstyle_t_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PLQ_plq_lightstyle_t_identifier, &PLQ_plq_lightstyle_t_verify_table);
}

static inline int PLQ_plq_lightstyle_t_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PLQ_plq_lightstyle_t_type_identifier, &PLQ_plq_lightstyle_t_verify_table);
}

static inline int PLQ_plq_lightstyle_t_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PLQ_plq_lightstyle_t_verify_table);
}

static inline int PLQ_plq_lightstyle_t_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PLQ_plq_lightstyle_t_verify_table);
}

static int PLQ_plq_lightstyles_t_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_table_vector_field(td, 0, 0, &PLQ_plq_lightstyle_t_verify_table) /* styles */)) return ret;
    return flatcc_verify_ok;
}

static inline int PLQ_plq_lightstyles_t_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PLQ_plq_lightstyles_t_identifier, &PLQ_plq_lightstyles_t_verify_table);
}

static inline int PLQ_plq_lightstyles_t_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PLQ_plq_lightstyles_t_type_identifier, &PLQ_plq_lightstyles_t_verify_table);
}

static inline int PLQ_plq_lightstyles_t_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PLQ_plq_lightstyles_t_verify_table);
}

static inline int PLQ_plq_lightstyles_t_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PLQ_plq_lightstyles_t_verify_table);
}

static int PLQ_plq_disconnect_t_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* reason */)) return ret;
    return flatcc_verify_ok;
}

static inline int PLQ_plq_disconnect_t_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PLQ_plq_disconnect_t_identifier, &PLQ_plq_disconnect_t_verify_table);
}

static inline int PLQ_plq_disconnect_t_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PLQ_plq_disconnect_t_type_identifier, &PLQ_plq_disconnect_t_verify_table);
}

static inline int PLQ_plq_disconnect_t_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PLQ_plq_disconnect_t_verify_table);
}

static inline int PLQ_plq_disconnect_t_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PLQ_plq_disconnect_t_verify_table);
}

static int PLQ_plq_input_t_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 24, 4) /* cmd */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 1, 1) /* msec */)) return ret;
    return flatcc_verify_ok;
}

static inline int PLQ_plq_input_t_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PLQ_plq_input_t_identifier, &PLQ_plq_input_t_verify_table);
}

static inline int PLQ_plq_input_t_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PLQ_plq_input_t_type_identifier, &PLQ_plq_input_t_verify_table);
}

static inline int PLQ_plq_input_t_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PLQ_plq_input_t_verify_table);
}

static inline int PLQ_plq_input_t_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PLQ_plq_input_t_verify_table);
}

static int PLQ_plq_command_t_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_string_field(td, 0, 0) /* text */)) return ret;
    return flatcc_verify_ok;
}

static inline int PLQ_plq_command_t_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PLQ_plq_command_t_identifier, &PLQ_plq_command_t_verify_table);
}

static inline int PLQ_plq_command_t_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PLQ_plq_command_t_type_identifier, &PLQ_plq_command_t_verify_table);
}

static inline int PLQ_plq_command_t_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PLQ_plq_command_t_verify_table);
}

static inline int PLQ_plq_command_t_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PLQ_plq_command_t_verify_table);
}

static int PLQ_plq_resourcereq_t_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* type */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 2, 2) /* index */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* name */)) return ret;
    return flatcc_verify_ok;
}

static inline int PLQ_plq_resourcereq_t_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PLQ_plq_resourcereq_t_identifier, &PLQ_plq_resourcereq_t_verify_table);
}

static inline int PLQ_plq_resourcereq_t_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PLQ_plq_resourcereq_t_type_identifier, &PLQ_plq_resourcereq_t_verify_table);
}

static inline int PLQ_plq_resourcereq_t_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PLQ_plq_resourcereq_t_verify_table);
}

static inline int PLQ_plq_resourcereq_t_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PLQ_plq_resourcereq_t_verify_table);
}

static int PLQ_plq_resourceresp_t_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* type */)) return ret;
    if ((ret = flatcc_verify_field(td, 1, 2, 2) /* index */)) return ret;
    if ((ret = flatcc_verify_string_field(td, 2, 0) /* name */)) return ret;
    if ((ret = flatcc_verify_vector_field(td, 3, 0, 1, 1, INT64_C(4294967295)) /* data */)) return ret;
    return flatcc_verify_ok;
}

static inline int PLQ_plq_resourceresp_t_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PLQ_plq_resourceresp_t_identifier, &PLQ_plq_resourceresp_t_verify_table);
}

static inline int PLQ_plq_resourceresp_t_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PLQ_plq_resourceresp_t_type_identifier, &PLQ_plq_resourceresp_t_verify_table);
}

static inline int PLQ_plq_resourceresp_t_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PLQ_plq_resourceresp_t_verify_table);
}

static inline int PLQ_plq_resourceresp_t_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PLQ_plq_resourceresp_t_verify_table);
}

static int PLQ_plq_message_t_verify_table(flatcc_table_verifier_descriptor_t *td)
{
    int ret;
    if ((ret = flatcc_verify_field(td, 0, 1, 1) /* type */)) return ret;
    if ((ret = flatcc_verify_union_field(td, 2, 0, &PLQ_plq_payload_t_union_verifier) /* payload */)) return ret;
    return flatcc_verify_ok;
}

static inline int PLQ_plq_message_t_verify_as_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PLQ_plq_message_t_identifier, &PLQ_plq_message_t_verify_table);
}

static inline int PLQ_plq_message_t_verify_as_typed_root(const void *buf, size_t bufsiz)
{
    return flatcc_verify_table_as_root(buf, bufsiz, PLQ_plq_message_t_type_identifier, &PLQ_plq_message_t_verify_table);
}

static inline int PLQ_plq_message_t_verify_as_root_with_identifier(const void *buf, size_t bufsiz, const char *fid)
{
    return flatcc_verify_table_as_root(buf, bufsiz, fid, &PLQ_plq_message_t_verify_table);
}

static inline int PLQ_plq_message_t_verify_as_root_with_type_hash(const void *buf, size_t bufsiz, flatbuffers_thash_t thash)
{
    return flatcc_verify_table_as_typed_root(buf, bufsiz, thash, &PLQ_plq_message_t_verify_table);
}

#include "flatcc/flatcc_epilogue.h"
#endif /* PLQ_VERIFIER_H */
