#ifndef PLQ_BUILDER_H
#define PLQ_BUILDER_H

/* Generated by flatcc 0.6.1 FlatBuffers schema compiler for C by dvide.com */

#ifndef PLQ_READER_H
#include "plq_reader.h"
#endif
#ifndef FLATBUFFERS_COMMON_BUILDER_H
#include "flatbuffers_common_builder.h"
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif

#define __PLQ_plq_resource_type_t_formal_args , PLQ_plq_resource_type_t_enum_t v0
#define __PLQ_plq_resource_type_t_call_args , v0
__flatbuffers_build_scalar(flatbuffers_, PLQ_plq_resource_type_t, PLQ_plq_resource_type_t_enum_t)
#define __PLQ_plq_msgtype_t_formal_args , PLQ_plq_msgtype_t_enum_t v0
#define __PLQ_plq_msgtype_t_call_args , v0
__flatbuffers_build_scalar(flatbuffers_, PLQ_plq_msgtype_t, PLQ_plq_msgtype_t_enum_t)

#define __PLQ_usercmd_t_formal_args ,\
  float v0, float v1, float v2, float v3, float v4, float v5
#define __PLQ_usercmd_t_call_args ,\
  v0, v1, v2, v3, v4, v5
static inline PLQ_usercmd_t_t *PLQ_usercmd_t_assign(PLQ_usercmd_t_t *p,
  float v0, float v1, float v2, float v3, float v4, float v5)
{ p->viewangles_x = v0; p->viewangles_y = v1; p->viewangles_z = v2; p->forwardmove = v3;
  p->sidemove = v4; p->upmove = v5;
  return p; }
static inline PLQ_usercmd_t_t *PLQ_usercmd_t_copy(PLQ_usercmd_t_t *p, const PLQ_usercmd_t_t *p2)
{ p->viewangles_x = p2->viewangles_x; p->viewangles_y = p2->viewangles_y; p->viewangles_z = p2->viewangles_z; p->forwardmove = p2->forwardmove;
  p->sidemove = p2->sidemove; p->upmove = p2->upmove;
  return p; }
static inline PLQ_usercmd_t_t *PLQ_usercmd_t_assign_to_pe(PLQ_usercmd_t_t *p,
  float v0, float v1, float v2, float v3, float v4, float v5)
{ flatbuffers_float_assign_to_pe(&p->viewangles_x, v0); flatbuffers_float_assign_to_pe(&p->viewangles_y, v1); flatbuffers_float_assign_to_pe(&p->viewangles_z, v2); flatbuffers_float_assign_to_pe(&p->forwardmove, v3);
  flatbuffers_float_assign_to_pe(&p->sidemove, v4); flatbuffers_float_assign_to_pe(&p->upmove, v5);
  return p; }
static inline PLQ_usercmd_t_t *PLQ_usercmd_t_copy_to_pe(PLQ_usercmd_t_t *p, const PLQ_usercmd_t_t *p2)
{ flatbuffers_float_copy_to_pe(&p->viewangles_x, &p2->viewangles_x); flatbuffers_float_copy_to_pe(&p->viewangles_y, &p2->viewangles_y); flatbuffers_float_copy_to_pe(&p->viewangles_z, &p2->viewangles_z); flatbuffers_float_copy_to_pe(&p->forwardmove, &p2->forwardmove);
  flatbuffers_float_copy_to_pe(&p->sidemove, &p2->sidemove); flatbuffers_float_copy_to_pe(&p->upmove, &p2->upmove);
  return p; }
static inline PLQ_usercmd_t_t *PLQ_usercmd_t_assign_from_pe(PLQ_usercmd_t_t *p,
  float v0, float v1, float v2, float v3, float v4, float v5)
{ flatbuffers_float_assign_from_pe(&p->viewangles_x, v0); flatbuffers_float_assign_from_pe(&p->viewangles_y, v1); flatbuffers_float_assign_from_pe(&p->viewangles_z, v2); flatbuffers_float_assign_from_pe(&p->forwardmove, v3);
  flatbuffers_float_assign_from_pe(&p->sidemove, v4); flatbuffers_float_assign_from_pe(&p->upmove, v5);
  return p; }
static inline PLQ_usercmd_t_t *PLQ_usercmd_t_copy_from_pe(PLQ_usercmd_t_t *p, const PLQ_usercmd_t_t *p2)
{ flatbuffers_float_copy_from_pe(&p->viewangles_x, &p2->viewangles_x); flatbuffers_float_copy_from_pe(&p->viewangles_y, &p2->viewangles_y); flatbuffers_float_copy_from_pe(&p->viewangles_z, &p2->viewangles_z); flatbuffers_float_copy_from_pe(&p->forwardmove, &p2->forwardmove);
  flatbuffers_float_copy_from_pe(&p->sidemove, &p2->sidemove); flatbuffers_float_copy_from_pe(&p->upmove, &p2->upmove);
  return p; }
__flatbuffers_build_struct(flatbuffers_, PLQ_usercmd_t, 24, 4, PLQ_usercmd_t_file_identifier, PLQ_usercmd_t_type_identifier)
__flatbuffers_define_fixed_array_primitives(flatbuffers_, PLQ_usercmd_t, PLQ_usercmd_t_t)

#define __PLQ_entity_state_t_formal_args ,\
  float v0, float v1, float v2, float v3,\
  float v4, float v5, uint16_t v6, uint16_t v7,\
  uint8_t v8, uint8_t v9, uint8_t v10, uint8_t v11, int32_t v12
#define __PLQ_entity_state_t_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6, v7,\
  v8, v9, v10, v11, v12
static inline PLQ_entity_state_t_t *PLQ_entity_state_t_assign(PLQ_entity_state_t_t *p,
  float v0, float v1, float v2, float v3,
  float v4, float v5, uint16_t v6, uint16_t v7,
  uint8_t v8, uint8_t v9, uint8_t v10, uint8_t v11, int32_t v12)
{ p->origin_x = v0; p->origin_y = v1; p->origin_z = v2; p->angles_x = v3;
  p->angles_y = v4; p->angles_z = v5; p->modelindex = v6; p->frame = v7;
  p->colormap = v8; p->skin = v9; p->alpha = v10; p->scale = v11;
  p->effects = v12;
  return p; }
static inline PLQ_entity_state_t_t *PLQ_entity_state_t_copy(PLQ_entity_state_t_t *p, const PLQ_entity_state_t_t *p2)
{ p->origin_x = p2->origin_x; p->origin_y = p2->origin_y; p->origin_z = p2->origin_z; p->angles_x = p2->angles_x;
  p->angles_y = p2->angles_y; p->angles_z = p2->angles_z; p->modelindex = p2->modelindex; p->frame = p2->frame;
  p->colormap = p2->colormap; p->skin = p2->skin; p->alpha = p2->alpha; p->scale = p2->scale;
  p->effects = p2->effects;
  return p; }
static inline PLQ_entity_state_t_t *PLQ_entity_state_t_assign_to_pe(PLQ_entity_state_t_t *p,
  float v0, float v1, float v2, float v3,
  float v4, float v5, uint16_t v6, uint16_t v7,
  uint8_t v8, uint8_t v9, uint8_t v10, uint8_t v11, int32_t v12)
{ flatbuffers_float_assign_to_pe(&p->origin_x, v0); flatbuffers_float_assign_to_pe(&p->origin_y, v1); flatbuffers_float_assign_to_pe(&p->origin_z, v2); flatbuffers_float_assign_to_pe(&p->angles_x, v3);
  flatbuffers_float_assign_to_pe(&p->angles_y, v4); flatbuffers_float_assign_to_pe(&p->angles_z, v5); flatbuffers_uint16_assign_to_pe(&p->modelindex, v6); flatbuffers_uint16_assign_to_pe(&p->frame, v7);
  p->colormap = v8; p->skin = v9; p->alpha = v10; p->scale = v11;
  flatbuffers_int32_assign_to_pe(&p->effects, v12);
  return p; }
static inline PLQ_entity_state_t_t *PLQ_entity_state_t_copy_to_pe(PLQ_entity_state_t_t *p, const PLQ_entity_state_t_t *p2)
{ flatbuffers_float_copy_to_pe(&p->origin_x, &p2->origin_x); flatbuffers_float_copy_to_pe(&p->origin_y, &p2->origin_y); flatbuffers_float_copy_to_pe(&p->origin_z, &p2->origin_z); flatbuffers_float_copy_to_pe(&p->angles_x, &p2->angles_x);
  flatbuffers_float_copy_to_pe(&p->angles_y, &p2->angles_y); flatbuffers_float_copy_to_pe(&p->angles_z, &p2->angles_z); flatbuffers_uint16_copy_to_pe(&p->modelindex, &p2->modelindex); flatbuffers_uint16_copy_to_pe(&p->frame, &p2->frame);
  p->colormap = p2->colormap; p->skin = p2->skin; p->alpha = p2->alpha; p->scale = p2->scale;
  flatbuffers_int32_copy_to_pe(&p->effects, &p2->effects);
  return p; }
static inline PLQ_entity_state_t_t *PLQ_entity_state_t_assign_from_pe(PLQ_entity_state_t_t *p,
  float v0, float v1, float v2, float v3,
  float v4, float v5, uint16_t v6, uint16_t v7,
  uint8_t v8, uint8_t v9, uint8_t v10, uint8_t v11, int32_t v12)
{ flatbuffers_float_assign_from_pe(&p->origin_x, v0); flatbuffers_float_assign_from_pe(&p->origin_y, v1); flatbuffers_float_assign_from_pe(&p->origin_z, v2); flatbuffers_float_assign_from_pe(&p->angles_x, v3);
  flatbuffers_float_assign_from_pe(&p->angles_y, v4); flatbuffers_float_assign_from_pe(&p->angles_z, v5); flatbuffers_uint16_assign_from_pe(&p->modelindex, v6); flatbuffers_uint16_assign_from_pe(&p->frame, v7);
  p->colormap = v8; p->skin = v9; p->alpha = v10; p->scale = v11;
  flatbuffers_int32_assign_from_pe(&p->effects, v12);
  return p; }
static inline PLQ_entity_state_t_t *PLQ_entity_state_t_copy_from_pe(PLQ_entity_state_t_t *p, const PLQ_entity_state_t_t *p2)
{ flatbuffers_float_copy_from_pe(&p->origin_x, &p2->origin_x); flatbuffers_float_copy_from_pe(&p->origin_y, &p2->origin_y); flatbuffers_float_copy_from_pe(&p->origin_z, &p2->origin_z); flatbuffers_float_copy_from_pe(&p->angles_x, &p2->angles_x);
  flatbuffers_float_copy_from_pe(&p->angles_y, &p2->angles_y); flatbuffers_float_copy_from_pe(&p->angles_z, &p2->angles_z); flatbuffers_uint16_copy_from_pe(&p->modelindex, &p2->modelindex); flatbuffers_uint16_copy_from_pe(&p->frame, &p2->frame);
  p->colormap = p2->colormap; p->skin = p2->skin; p->alpha = p2->alpha; p->scale = p2->scale;
  flatbuffers_int32_copy_from_pe(&p->effects, &p2->effects);
  return p; }
__flatbuffers_build_struct(flatbuffers_, PLQ_entity_state_t, 36, 4, PLQ_entity_state_t_file_identifier, PLQ_entity_state_t_type_identifier)
__flatbuffers_define_fixed_array_primitives(flatbuffers_, PLQ_entity_state_t, PLQ_entity_state_t_t)

#define __PLQ_dlight_t_formal_args ,\
  float v0, float v1, float v2, float v3,\
  float v4, float v5, float v6, float v7,\
  int32_t v8, float v9, float v10, float v11
#define __PLQ_dlight_t_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6, v7,\
  v8, v9, v10, v11
static inline PLQ_dlight_t_t *PLQ_dlight_t_assign(PLQ_dlight_t_t *p,
  float v0, float v1, float v2, float v3,
  float v4, float v5, float v6, float v7,
  int32_t v8, float v9, float v10, float v11)
{ p->origin_x = v0; p->origin_y = v1; p->origin_z = v2; p->radius = v3;
  p->spawn = v4; p->die = v5; p->decay = v6; p->minlight = v7;
  p->key = v8; p->color_r = v9; p->color_g = v10; p->color_b = v11;
  return p; }
static inline PLQ_dlight_t_t *PLQ_dlight_t_copy(PLQ_dlight_t_t *p, const PLQ_dlight_t_t *p2)
{ p->origin_x = p2->origin_x; p->origin_y = p2->origin_y; p->origin_z = p2->origin_z; p->radius = p2->radius;
  p->spawn = p2->spawn; p->die = p2->die; p->decay = p2->decay; p->minlight = p2->minlight;
  p->key = p2->key; p->color_r = p2->color_r; p->color_g = p2->color_g; p->color_b = p2->color_b;
  return p; }
static inline PLQ_dlight_t_t *PLQ_dlight_t_assign_to_pe(PLQ_dlight_t_t *p,
  float v0, float v1, float v2, float v3,
  float v4, float v5, float v6, float v7,
  int32_t v8, float v9, float v10, float v11)
{ flatbuffers_float_assign_to_pe(&p->origin_x, v0); flatbuffers_float_assign_to_pe(&p->origin_y, v1); flatbuffers_float_assign_to_pe(&p->origin_z, v2); flatbuffers_float_assign_to_pe(&p->radius, v3);
  flatbuffers_float_assign_to_pe(&p->spawn, v4); flatbuffers_float_assign_to_pe(&p->die, v5); flatbuffers_float_assign_to_pe(&p->decay, v6); flatbuffers_float_assign_to_pe(&p->minlight, v7);
  flatbuffers_int32_assign_to_pe(&p->key, v8); flatbuffers_float_assign_to_pe(&p->color_r, v9); flatbuffers_float_assign_to_pe(&p->color_g, v10); flatbuffers_float_assign_to_pe(&p->color_b, v11);
  return p; }
static inline PLQ_dlight_t_t *PLQ_dlight_t_copy_to_pe(PLQ_dlight_t_t *p, const PLQ_dlight_t_t *p2)
{ flatbuffers_float_copy_to_pe(&p->origin_x, &p2->origin_x); flatbuffers_float_copy_to_pe(&p->origin_y, &p2->origin_y); flatbuffers_float_copy_to_pe(&p->origin_z, &p2->origin_z); flatbuffers_float_copy_to_pe(&p->radius, &p2->radius);
  flatbuffers_float_copy_to_pe(&p->spawn, &p2->spawn); flatbuffers_float_copy_to_pe(&p->die, &p2->die); flatbuffers_float_copy_to_pe(&p->decay, &p2->decay); flatbuffers_float_copy_to_pe(&p->minlight, &p2->minlight);
  flatbuffers_int32_copy_to_pe(&p->key, &p2->key); flatbuffers_float_copy_to_pe(&p->color_r, &p2->color_r); flatbuffers_float_copy_to_pe(&p->color_g, &p2->color_g); flatbuffers_float_copy_to_pe(&p->color_b, &p2->color_b);
  return p; }
static inline PLQ_dlight_t_t *PLQ_dlight_t_assign_from_pe(PLQ_dlight_t_t *p,
  float v0, float v1, float v2, float v3,
  float v4, float v5, float v6, float v7,
  int32_t v8, float v9, float v10, float v11)
{ flatbuffers_float_assign_from_pe(&p->origin_x, v0); flatbuffers_float_assign_from_pe(&p->origin_y, v1); flatbuffers_float_assign_from_pe(&p->origin_z, v2); flatbuffers_float_assign_from_pe(&p->radius, v3);
  flatbuffers_float_assign_from_pe(&p->spawn, v4); flatbuffers_float_assign_from_pe(&p->die, v5); flatbuffers_float_assign_from_pe(&p->decay, v6); flatbuffers_float_assign_from_pe(&p->minlight, v7);
  flatbuffers_int32_assign_from_pe(&p->key, v8); flatbuffers_float_assign_from_pe(&p->color_r, v9); flatbuffers_float_assign_from_pe(&p->color_g, v10); flatbuffers_float_assign_from_pe(&p->color_b, v11);
  return p; }
static inline PLQ_dlight_t_t *PLQ_dlight_t_copy_from_pe(PLQ_dlight_t_t *p, const PLQ_dlight_t_t *p2)
{ flatbuffers_float_copy_from_pe(&p->origin_x, &p2->origin_x); flatbuffers_float_copy_from_pe(&p->origin_y, &p2->origin_y); flatbuffers_float_copy_from_pe(&p->origin_z, &p2->origin_z); flatbuffers_float_copy_from_pe(&p->radius, &p2->radius);
  flatbuffers_float_copy_from_pe(&p->spawn, &p2->spawn); flatbuffers_float_copy_from_pe(&p->die, &p2->die); flatbuffers_float_copy_from_pe(&p->decay, &p2->decay); flatbuffers_float_copy_from_pe(&p->minlight, &p2->minlight);
  flatbuffers_int32_copy_from_pe(&p->key, &p2->key); flatbuffers_float_copy_from_pe(&p->color_r, &p2->color_r); flatbuffers_float_copy_from_pe(&p->color_g, &p2->color_g); flatbuffers_float_copy_from_pe(&p->color_b, &p2->color_b);
  return p; }
__flatbuffers_build_struct(flatbuffers_, PLQ_dlight_t, 48, 4, PLQ_dlight_t_file_identifier, PLQ_dlight_t_type_identifier)
__flatbuffers_define_fixed_array_primitives(flatbuffers_, PLQ_dlight_t, PLQ_dlight_t_t)

#define __PLQ_cshift_t_formal_args , int32_t v0, int32_t v1, int32_t v2, float v3
#define __PLQ_cshift_t_call_args , v0, v1, v2, v3
static inline PLQ_cshift_t_t *PLQ_cshift_t_assign(PLQ_cshift_t_t *p, int32_t v0, int32_t v1, int32_t v2, float v3)
{ p->destcolor_r = v0; p->destcolor_g = v1; p->destcolor_b = v2; p->percent = v3;
  return p; }
static inline PLQ_cshift_t_t *PLQ_cshift_t_copy(PLQ_cshift_t_t *p, const PLQ_cshift_t_t *p2)
{ p->destcolor_r = p2->destcolor_r; p->destcolor_g = p2->destcolor_g; p->destcolor_b = p2->destcolor_b; p->percent = p2->percent;
  return p; }
static inline PLQ_cshift_t_t *PLQ_cshift_t_assign_to_pe(PLQ_cshift_t_t *p, int32_t v0, int32_t v1, int32_t v2, float v3)
{ flatbuffers_int32_assign_to_pe(&p->destcolor_r, v0); flatbuffers_int32_assign_to_pe(&p->destcolor_g, v1); flatbuffers_int32_assign_to_pe(&p->destcolor_b, v2); flatbuffers_float_assign_to_pe(&p->percent, v3);
  return p; }
static inline PLQ_cshift_t_t *PLQ_cshift_t_copy_to_pe(PLQ_cshift_t_t *p, const PLQ_cshift_t_t *p2)
{ flatbuffers_int32_copy_to_pe(&p->destcolor_r, &p2->destcolor_r); flatbuffers_int32_copy_to_pe(&p->destcolor_g, &p2->destcolor_g); flatbuffers_int32_copy_to_pe(&p->destcolor_b, &p2->destcolor_b); flatbuffers_float_copy_to_pe(&p->percent, &p2->percent);
  return p; }
static inline PLQ_cshift_t_t *PLQ_cshift_t_assign_from_pe(PLQ_cshift_t_t *p, int32_t v0, int32_t v1, int32_t v2, float v3)
{ flatbuffers_int32_assign_from_pe(&p->destcolor_r, v0); flatbuffers_int32_assign_from_pe(&p->destcolor_g, v1); flatbuffers_int32_assign_from_pe(&p->destcolor_b, v2); flatbuffers_float_assign_from_pe(&p->percent, v3);
  return p; }
static inline PLQ_cshift_t_t *PLQ_cshift_t_copy_from_pe(PLQ_cshift_t_t *p, const PLQ_cshift_t_t *p2)
{ flatbuffers_int32_copy_from_pe(&p->destcolor_r, &p2->destcolor_r); flatbuffers_int32_copy_from_pe(&p->destcolor_g, &p2->destcolor_g); flatbuffers_int32_copy_from_pe(&p->destcolor_b, &p2->destcolor_b); flatbuffers_float_copy_from_pe(&p->percent, &p2->percent);
  return p; }
__flatbuffers_build_struct(flatbuffers_, PLQ_cshift_t, 16, 4, PLQ_cshift_t_file_identifier, PLQ_cshift_t_type_identifier)
__flatbuffers_define_fixed_array_primitives(flatbuffers_, PLQ_cshift_t, PLQ_cshift_t_t)

#define __PLQ_plq_viewstate_t_formal_args ,\
  float v0, float v1, float v2, float v3,\
  float v4, float v5, float v6, float v7,\
  float v8, float v9, double v10, int16_t v11, uint16_t v12
#define __PLQ_plq_viewstate_t_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6, v7,\
  v8, v9, v10, v11, v12
static inline PLQ_plq_viewstate_t_t *PLQ_plq_viewstate_t_assign(PLQ_plq_viewstate_t_t *p,
  float v0, float v1, float v2, float v3,
  float v4, float v5, float v6, float v7,
  float v8, float v9, double v10, int16_t v11, uint16_t v12)
{ p->viewangles_x = v0; p->viewangles_y = v1; p->viewangles_z = v2; p->velocity_x = v3;
  p->velocity_y = v4; p->velocity_z = v5; p->punchangle_x = v6; p->punchangle_y = v7;
  p->punchangle_z = v8; p->viewheight = v9; p->time = v10; p->viewentity = v11;
  p->flags = v12;
  return p; }
static inline PLQ_plq_viewstate_t_t *PLQ_plq_viewstate_t_copy(PLQ_plq_viewstate_t_t *p, const PLQ_plq_viewstate_t_t *p2)
{ p->viewangles_x = p2->viewangles_x; p->viewangles_y = p2->viewangles_y; p->viewangles_z = p2->viewangles_z; p->velocity_x = p2->velocity_x;
  p->velocity_y = p2->velocity_y; p->velocity_z = p2->velocity_z; p->punchangle_x = p2->punchangle_x; p->punchangle_y = p2->punchangle_y;
  p->punchangle_z = p2->punchangle_z; p->viewheight = p2->viewheight; p->time = p2->time; p->viewentity = p2->viewentity;
  p->flags = p2->flags;
  return p; }
static inline PLQ_plq_viewstate_t_t *PLQ_plq_viewstate_t_assign_to_pe(PLQ_plq_viewstate_t_t *p,
  float v0, float v1, float v2, float v3,
  float v4, float v5, float v6, float v7,
  float v8, float v9, double v10, int16_t v11, uint16_t v12)
{ flatbuffers_float_assign_to_pe(&p->viewangles_x, v0); flatbuffers_float_assign_to_pe(&p->viewangles_y, v1); flatbuffers_float_assign_to_pe(&p->viewangles_z, v2); flatbuffers_float_assign_to_pe(&p->velocity_x, v3);
  flatbuffers_float_assign_to_pe(&p->velocity_y, v4); flatbuffers_float_assign_to_pe(&p->velocity_z, v5); flatbuffers_float_assign_to_pe(&p->punchangle_x, v6); flatbuffers_float_assign_to_pe(&p->punchangle_y, v7);
  flatbuffers_float_assign_to_pe(&p->punchangle_z, v8); flatbuffers_float_assign_to_pe(&p->viewheight, v9); flatbuffers_double_assign_to_pe(&p->time, v10); flatbuffers_int16_assign_to_pe(&p->viewentity, v11);
  flatbuffers_uint16_assign_to_pe(&p->flags, v12);
  return p; }
static inline PLQ_plq_viewstate_t_t *PLQ_plq_viewstate_t_copy_to_pe(PLQ_plq_viewstate_t_t *p, const PLQ_plq_viewstate_t_t *p2)
{ flatbuffers_float_copy_to_pe(&p->viewangles_x, &p2->viewangles_x); flatbuffers_float_copy_to_pe(&p->viewangles_y, &p2->viewangles_y); flatbuffers_float_copy_to_pe(&p->viewangles_z, &p2->viewangles_z); flatbuffers_float_copy_to_pe(&p->velocity_x, &p2->velocity_x);
  flatbuffers_float_copy_to_pe(&p->velocity_y, &p2->velocity_y); flatbuffers_float_copy_to_pe(&p->velocity_z, &p2->velocity_z); flatbuffers_float_copy_to_pe(&p->punchangle_x, &p2->punchangle_x); flatbuffers_float_copy_to_pe(&p->punchangle_y, &p2->punchangle_y);
  flatbuffers_float_copy_to_pe(&p->punchangle_z, &p2->punchangle_z); flatbuffers_float_copy_to_pe(&p->viewheight, &p2->viewheight); flatbuffers_double_copy_to_pe(&p->time, &p2->time); flatbuffers_int16_copy_to_pe(&p->viewentity, &p2->viewentity);
  flatbuffers_uint16_copy_to_pe(&p->flags, &p2->flags);
  return p; }
static inline PLQ_plq_viewstate_t_t *PLQ_plq_viewstate_t_assign_from_pe(PLQ_plq_viewstate_t_t *p,
  float v0, float v1, float v2, float v3,
  float v4, float v5, float v6, float v7,
  float v8, float v9, double v10, int16_t v11, uint16_t v12)
{ flatbuffers_float_assign_from_pe(&p->viewangles_x, v0); flatbuffers_float_assign_from_pe(&p->viewangles_y, v1); flatbuffers_float_assign_from_pe(&p->viewangles_z, v2); flatbuffers_float_assign_from_pe(&p->velocity_x, v3);
  flatbuffers_float_assign_from_pe(&p->velocity_y, v4); flatbuffers_float_assign_from_pe(&p->velocity_z, v5); flatbuffers_float_assign_from_pe(&p->punchangle_x, v6); flatbuffers_float_assign_from_pe(&p->punchangle_y, v7);
  flatbuffers_float_assign_from_pe(&p->punchangle_z, v8); flatbuffers_float_assign_from_pe(&p->viewheight, v9); flatbuffers_double_assign_from_pe(&p->time, v10); flatbuffers_int16_assign_from_pe(&p->viewentity, v11);
  flatbuffers_uint16_assign_from_pe(&p->flags, v12);
  return p; }
static inline PLQ_plq_viewstate_t_t *PLQ_plq_viewstate_t_copy_from_pe(PLQ_plq_viewstate_t_t *p, const PLQ_plq_viewstate_t_t *p2)
{ flatbuffers_float_copy_from_pe(&p->viewangles_x, &p2->viewangles_x); flatbuffers_float_copy_from_pe(&p->viewangles_y, &p2->viewangles_y); flatbuffers_float_copy_from_pe(&p->viewangles_z, &p2->viewangles_z); flatbuffers_float_copy_from_pe(&p->velocity_x, &p2->velocity_x);
  flatbuffers_float_copy_from_pe(&p->velocity_y, &p2->velocity_y); flatbuffers_float_copy_from_pe(&p->velocity_z, &p2->velocity_z); flatbuffers_float_copy_from_pe(&p->punchangle_x, &p2->punchangle_x); flatbuffers_float_copy_from_pe(&p->punchangle_y, &p2->punchangle_y);
  flatbuffers_float_copy_from_pe(&p->punchangle_z, &p2->punchangle_z); flatbuffers_float_copy_from_pe(&p->viewheight, &p2->viewheight); flatbuffers_double_copy_from_pe(&p->time, &p2->time); flatbuffers_int16_copy_from_pe(&p->viewentity, &p2->viewentity);
  flatbuffers_uint16_copy_from_pe(&p->flags, &p2->flags);
  return p; }
__flatbuffers_build_struct(flatbuffers_, PLQ_plq_viewstate_t, 56, 8, PLQ_plq_viewstate_t_file_identifier, PLQ_plq_viewstate_t_type_identifier)
__flatbuffers_define_fixed_array_primitives(flatbuffers_, PLQ_plq_viewstate_t, PLQ_plq_viewstate_t_t)

#define __PLQ_plq_stats_t_formal_args ,\
  int32_t v0, int32_t v1, int32_t v2, int32_t v3,\
  int32_t v4, int32_t v5, int32_t v6, int32_t v7,\
  int32_t v8, int32_t v9, int32_t v10, int32_t v11,\
  int32_t v12, int32_t v13, int32_t v14, uint32_t v15
#define __PLQ_plq_stats_t_call_args ,\
  v0, v1, v2, v3,\
  v4, v5, v6, v7,\
  v8, v9, v10, v11,\
  v12, v13, v14, v15
static inline PLQ_plq_stats_t_t *PLQ_plq_stats_t_assign(PLQ_plq_stats_t_t *p,
  int32_t v0, int32_t v1, int32_t v2, int32_t v3,
  int32_t v4, int32_t v5, int32_t v6, int32_t v7,
  int32_t v8, int32_t v9, int32_t v10, int32_t v11,
  int32_t v12, int32_t v13, int32_t v14, uint32_t v15)
{ p->health = v0; p->frags = v1; p->weapon = v2; p->ammo = v3;
  p->armor = v4; p->weaponframe = v5; p->shells = v6; p->nails = v7;
  p->rockets = v8; p->cells = v9; p->activeweapon = v10; p->totalsecrets = v11;
  p->totalmonsters = v12; p->secrets = v13; p->monsters = v14; p->items = v15;
  return p; }
static inline PLQ_plq_stats_t_t *PLQ_plq_stats_t_copy(PLQ_plq_stats_t_t *p, const PLQ_plq_stats_t_t *p2)
{ p->health = p2->health; p->frags = p2->frags; p->weapon = p2->weapon; p->ammo = p2->ammo;
  p->armor = p2->armor; p->weaponframe = p2->weaponframe; p->shells = p2->shells; p->nails = p2->nails;
  p->rockets = p2->rockets; p->cells = p2->cells; p->activeweapon = p2->activeweapon; p->totalsecrets = p2->totalsecrets;
  p->totalmonsters = p2->totalmonsters; p->secrets = p2->secrets; p->monsters = p2->monsters; p->items = p2->items;
  return p; }
static inline PLQ_plq_stats_t_t *PLQ_plq_stats_t_assign_to_pe(PLQ_plq_stats_t_t *p,
  int32_t v0, int32_t v1, int32_t v2, int32_t v3,
  int32_t v4, int32_t v5, int32_t v6, int32_t v7,
  int32_t v8, int32_t v9, int32_t v10, int32_t v11,
  int32_t v12, int32_t v13, int32_t v14, uint32_t v15)
{ flatbuffers_int32_assign_to_pe(&p->health, v0); flatbuffers_int32_assign_to_pe(&p->frags, v1); flatbuffers_int32_assign_to_pe(&p->weapon, v2); flatbuffers_int32_assign_to_pe(&p->ammo, v3);
  flatbuffers_int32_assign_to_pe(&p->armor, v4); flatbuffers_int32_assign_to_pe(&p->weaponframe, v5); flatbuffers_int32_assign_to_pe(&p->shells, v6); flatbuffers_int32_assign_to_pe(&p->nails, v7);
  flatbuffers_int32_assign_to_pe(&p->rockets, v8); flatbuffers_int32_assign_to_pe(&p->cells, v9); flatbuffers_int32_assign_to_pe(&p->activeweapon, v10); flatbuffers_int32_assign_to_pe(&p->totalsecrets, v11);
  flatbuffers_int32_assign_to_pe(&p->totalmonsters, v12); flatbuffers_int32_assign_to_pe(&p->secrets, v13); flatbuffers_int32_assign_to_pe(&p->monsters, v14); flatbuffers_uint32_assign_to_pe(&p->items, v15);
  return p; }
static inline PLQ_plq_stats_t_t *PLQ_plq_stats_t_copy_to_pe(PLQ_plq_stats_t_t *p, const PLQ_plq_stats_t_t *p2)
{ flatbuffers_int32_copy_to_pe(&p->health, &p2->health); flatbuffers_int32_copy_to_pe(&p->frags, &p2->frags); flatbuffers_int32_copy_to_pe(&p->weapon, &p2->weapon); flatbuffers_int32_copy_to_pe(&p->ammo, &p2->ammo);
  flatbuffers_int32_copy_to_pe(&p->armor, &p2->armor); flatbuffers_int32_copy_to_pe(&p->weaponframe, &p2->weaponframe); flatbuffers_int32_copy_to_pe(&p->shells, &p2->shells); flatbuffers_int32_copy_to_pe(&p->nails, &p2->nails);
  flatbuffers_int32_copy_to_pe(&p->rockets, &p2->rockets); flatbuffers_int32_copy_to_pe(&p->cells, &p2->cells); flatbuffers_int32_copy_to_pe(&p->activeweapon, &p2->activeweapon); flatbuffers_int32_copy_to_pe(&p->totalsecrets, &p2->totalsecrets);
  flatbuffers_int32_copy_to_pe(&p->totalmonsters, &p2->totalmonsters); flatbuffers_int32_copy_to_pe(&p->secrets, &p2->secrets); flatbuffers_int32_copy_to_pe(&p->monsters, &p2->monsters); flatbuffers_uint32_copy_to_pe(&p->items, &p2->items);
  return p; }
static inline PLQ_plq_stats_t_t *PLQ_plq_stats_t_assign_from_pe(PLQ_plq_stats_t_t *p,
  int32_t v0, int32_t v1, int32_t v2, int32_t v3,
  int32_t v4, int32_t v5, int32_t v6, int32_t v7,
  int32_t v8, int32_t v9, int32_t v10, int32_t v11,
  int32_t v12, int32_t v13, int32_t v14, uint32_t v15)
{ flatbuffers_int32_assign_from_pe(&p->health, v0); flatbuffers_int32_assign_from_pe(&p->frags, v1); flatbuffers_int32_assign_from_pe(&p->weapon, v2); flatbuffers_int32_assign_from_pe(&p->ammo, v3);
  flatbuffers_int32_assign_from_pe(&p->armor, v4); flatbuffers_int32_assign_from_pe(&p->weaponframe, v5); flatbuffers_int32_assign_from_pe(&p->shells, v6); flatbuffers_int32_assign_from_pe(&p->nails, v7);
  flatbuffers_int32_assign_from_pe(&p->rockets, v8); flatbuffers_int32_assign_from_pe(&p->cells, v9); flatbuffers_int32_assign_from_pe(&p->activeweapon, v10); flatbuffers_int32_assign_from_pe(&p->totalsecrets, v11);
  flatbuffers_int32_assign_from_pe(&p->totalmonsters, v12); flatbuffers_int32_assign_from_pe(&p->secrets, v13); flatbuffers_int32_assign_from_pe(&p->monsters, v14); flatbuffers_uint32_assign_from_pe(&p->items, v15);
  return p; }
static inline PLQ_plq_stats_t_t *PLQ_plq_stats_t_copy_from_pe(PLQ_plq_stats_t_t *p, const PLQ_plq_stats_t_t *p2)
{ flatbuffers_int32_copy_from_pe(&p->health, &p2->health); flatbuffers_int32_copy_from_pe(&p->frags, &p2->frags); flatbuffers_int32_copy_from_pe(&p->weapon, &p2->weapon); flatbuffers_int32_copy_from_pe(&p->ammo, &p2->ammo);
  flatbuffers_int32_copy_from_pe(&p->armor, &p2->armor); flatbuffers_int32_copy_from_pe(&p->weaponframe, &p2->weaponframe); flatbuffers_int32_copy_from_pe(&p->shells, &p2->shells); flatbuffers_int32_copy_from_pe(&p->nails, &p2->nails);
  flatbuffers_int32_copy_from_pe(&p->rockets, &p2->rockets); flatbuffers_int32_copy_from_pe(&p->cells, &p2->cells); flatbuffers_int32_copy_from_pe(&p->activeweapon, &p2->activeweapon); flatbuffers_int32_copy_from_pe(&p->totalsecrets, &p2->totalsecrets);
  flatbuffers_int32_copy_from_pe(&p->totalmonsters, &p2->totalmonsters); flatbuffers_int32_copy_from_pe(&p->secrets, &p2->secrets); flatbuffers_int32_copy_from_pe(&p->monsters, &p2->monsters); flatbuffers_uint32_copy_from_pe(&p->items, &p2->items);
  return p; }
__flatbuffers_build_struct(flatbuffers_, PLQ_plq_stats_t, 64, 4, PLQ_plq_stats_t_file_identifier, PLQ_plq_stats_t_type_identifier)
__flatbuffers_define_fixed_array_primitives(flatbuffers_, PLQ_plq_stats_t, PLQ_plq_stats_t_t)

typedef flatbuffers_union_ref_t PLQ_plq_payload_t_union_ref_t;
typedef flatbuffers_union_vec_ref_t PLQ_plq_payload_t_union_vec_ref_t;
static PLQ_plq_payload_t_union_ref_t PLQ_plq_payload_t_clone(flatbuffers_builder_t *B, PLQ_plq_payload_t_union_t t);

static const flatbuffers_voffset_t __PLQ_plq_frame_t_required[] = { 0 };
typedef flatbuffers_ref_t PLQ_plq_frame_t_ref_t;
static PLQ_plq_frame_t_ref_t PLQ_plq_frame_t_clone(flatbuffers_builder_t *B, PLQ_plq_frame_t_table_t t);
__flatbuffers_build_table(flatbuffers_, PLQ_plq_frame_t, 5)

static const flatbuffers_voffset_t __PLQ_plq_mapchange_t_required[] = { 0 };
typedef flatbuffers_ref_t PLQ_plq_mapchange_t_ref_t;
static PLQ_plq_mapchange_t_ref_t PLQ_plq_mapchange_t_clone(flatbuffers_builder_t *B, PLQ_plq_mapchange_t_table_t t);
__flatbuffers_build_table(flatbuffers_, PLQ_plq_mapchange_t, 4)

static const flatbuffers_voffset_t __PLQ_plq_lightstyle_t_required[] = { 0 };
typedef flatbuffers_ref_t PLQ_plq_lightstyle_t_ref_t;
static PLQ_plq_lightstyle_t_ref_t PLQ_plq_lightstyle_t_clone(flatbuffers_builder_t *B, PLQ_plq_lightstyle_t_table_t t);
__flatbuffers_build_table(flatbuffers_, PLQ_plq_lightstyle_t, 2)

static const flatbuffers_voffset_t __PLQ_plq_lightstyles_t_required[] = { 0 };
typedef flatbuffers_ref_t PLQ_plq_lightstyles_t_ref_t;
static PLQ_plq_lightstyles_t_ref_t PLQ_plq_lightstyles_t_clone(flatbuffers_builder_t *B, PLQ_plq_lightstyles_t_table_t t);
__flatbuffers_build_table(flatbuffers_, PLQ_plq_lightstyles_t, 1)

static const flatbuffers_voffset_t __PLQ_plq_disconnect_t_required[] = { 0 };
typedef flatbuffers_ref_t PLQ_plq_disconnect_t_ref_t;
static PLQ_plq_disconnect_t_ref_t PLQ_plq_disconnect_t_clone(flatbuffers_builder_t *B, PLQ_plq_disconnect_t_table_t t);
__flatbuffers_build_table(flatbuffers_, PLQ_plq_disconnect_t, 1)

static const flatbuffers_voffset_t __PLQ_plq_input_t_required[] = { 0 };
typedef flatbuffers_ref_t PLQ_plq_input_t_ref_t;
static PLQ_plq_input_t_ref_t PLQ_plq_input_t_clone(flatbuffers_builder_t *B, PLQ_plq_input_t_table_t t);
__flatbuffers_build_table(flatbuffers_, PLQ_plq_input_t, 2)

static const flatbuffers_voffset_t __PLQ_plq_command_t_required[] = { 0 };
typedef flatbuffers_ref_t PLQ_plq_command_t_ref_t;
static PLQ_plq_command_t_ref_t PLQ_plq_command_t_clone(flatbuffers_builder_t *B, PLQ_plq_command_t_table_t t);
__flatbuffers_build_table(flatbuffers_, PLQ_plq_command_t, 1)

static const flatbuffers_voffset_t __PLQ_plq_resourcereq_t_required[] = { 0 };
typedef flatbuffers_ref_t PLQ_plq_resourcereq_t_ref_t;
static PLQ_plq_resourcereq_t_ref_t PLQ_plq_resourcereq_t_clone(flatbuffers_builder_t *B, PLQ_plq_resourcereq_t_table_t t);
__flatbuffers_build_table(flatbuffers_, PLQ_plq_resourcereq_t, 3)

static const flatbuffers_voffset_t __PLQ_plq_resourceresp_t_required[] = { 0 };
typedef flatbuffers_ref_t PLQ_plq_resourceresp_t_ref_t;
static PLQ_plq_resourceresp_t_ref_t PLQ_plq_resourceresp_t_clone(flatbuffers_builder_t *B, PLQ_plq_resourceresp_t_table_t t);
__flatbuffers_build_table(flatbuffers_, PLQ_plq_resourceresp_t, 4)

static const flatbuffers_voffset_t __PLQ_plq_message_t_required[] = { 0 };
typedef flatbuffers_ref_t PLQ_plq_message_t_ref_t;
static PLQ_plq_message_t_ref_t PLQ_plq_message_t_clone(flatbuffers_builder_t *B, PLQ_plq_message_t_table_t t);
__flatbuffers_build_table(flatbuffers_, PLQ_plq_message_t, 3)

#define __PLQ_plq_frame_t_formal_args ,\
  PLQ_plq_viewstate_t_t *v0, PLQ_plq_stats_t_t *v1, PLQ_entity_state_t_vec_ref_t v2, PLQ_dlight_t_vec_ref_t v3, PLQ_cshift_t_vec_ref_t v4
#define __PLQ_plq_frame_t_call_args ,\
  v0, v1, v2, v3, v4
static inline PLQ_plq_frame_t_ref_t PLQ_plq_frame_t_create(flatbuffers_builder_t *B __PLQ_plq_frame_t_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PLQ_plq_frame_t, PLQ_plq_frame_t_file_identifier, PLQ_plq_frame_t_type_identifier)

#define __PLQ_plq_mapchange_t_formal_args , flatbuffers_string_ref_t v0, flatbuffers_string_ref_t v1, uint8_t v2, uint8_t v3
#define __PLQ_plq_mapchange_t_call_args , v0, v1, v2, v3
static inline PLQ_plq_mapchange_t_ref_t PLQ_plq_mapchange_t_create(flatbuffers_builder_t *B __PLQ_plq_mapchange_t_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PLQ_plq_mapchange_t, PLQ_plq_mapchange_t_file_identifier, PLQ_plq_mapchange_t_type_identifier)

#define __PLQ_plq_lightstyle_t_formal_args , uint8_t v0, flatbuffers_string_ref_t v1
#define __PLQ_plq_lightstyle_t_call_args , v0, v1
static inline PLQ_plq_lightstyle_t_ref_t PLQ_plq_lightstyle_t_create(flatbuffers_builder_t *B __PLQ_plq_lightstyle_t_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PLQ_plq_lightstyle_t, PLQ_plq_lightstyle_t_file_identifier, PLQ_plq_lightstyle_t_type_identifier)

#define __PLQ_plq_lightstyles_t_formal_args , PLQ_plq_lightstyle_t_vec_ref_t v0
#define __PLQ_plq_lightstyles_t_call_args , v0
static inline PLQ_plq_lightstyles_t_ref_t PLQ_plq_lightstyles_t_create(flatbuffers_builder_t *B __PLQ_plq_lightstyles_t_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PLQ_plq_lightstyles_t, PLQ_plq_lightstyles_t_file_identifier, PLQ_plq_lightstyles_t_type_identifier)

#define __PLQ_plq_disconnect_t_formal_args , flatbuffers_string_ref_t v0
#define __PLQ_plq_disconnect_t_call_args , v0
static inline PLQ_plq_disconnect_t_ref_t PLQ_plq_disconnect_t_create(flatbuffers_builder_t *B __PLQ_plq_disconnect_t_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PLQ_plq_disconnect_t, PLQ_plq_disconnect_t_file_identifier, PLQ_plq_disconnect_t_type_identifier)

#define __PLQ_plq_input_t_formal_args , PLQ_usercmd_t_t *v0, uint8_t v1
#define __PLQ_plq_input_t_call_args , v0, v1
static inline PLQ_plq_input_t_ref_t PLQ_plq_input_t_create(flatbuffers_builder_t *B __PLQ_plq_input_t_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PLQ_plq_input_t, PLQ_plq_input_t_file_identifier, PLQ_plq_input_t_type_identifier)

#define __PLQ_plq_command_t_formal_args , flatbuffers_string_ref_t v0
#define __PLQ_plq_command_t_call_args , v0
static inline PLQ_plq_command_t_ref_t PLQ_plq_command_t_create(flatbuffers_builder_t *B __PLQ_plq_command_t_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PLQ_plq_command_t, PLQ_plq_command_t_file_identifier, PLQ_plq_command_t_type_identifier)

#define __PLQ_plq_resourcereq_t_formal_args , PLQ_plq_resource_type_t_enum_t v0, uint16_t v1, flatbuffers_string_ref_t v2
#define __PLQ_plq_resourcereq_t_call_args , v0, v1, v2
static inline PLQ_plq_resourcereq_t_ref_t PLQ_plq_resourcereq_t_create(flatbuffers_builder_t *B __PLQ_plq_resourcereq_t_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PLQ_plq_resourcereq_t, PLQ_plq_resourcereq_t_file_identifier, PLQ_plq_resourcereq_t_type_identifier)

#define __PLQ_plq_resourceresp_t_formal_args , PLQ_plq_resource_type_t_enum_t v0, uint16_t v1, flatbuffers_string_ref_t v2, flatbuffers_uint8_vec_ref_t v3
#define __PLQ_plq_resourceresp_t_call_args , v0, v1, v2, v3
static inline PLQ_plq_resourceresp_t_ref_t PLQ_plq_resourceresp_t_create(flatbuffers_builder_t *B __PLQ_plq_resourceresp_t_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PLQ_plq_resourceresp_t, PLQ_plq_resourceresp_t_file_identifier, PLQ_plq_resourceresp_t_type_identifier)

#define __PLQ_plq_message_t_formal_args , PLQ_plq_msgtype_t_enum_t v0, PLQ_plq_payload_t_union_ref_t v2
#define __PLQ_plq_message_t_call_args , v0, v2
static inline PLQ_plq_message_t_ref_t PLQ_plq_message_t_create(flatbuffers_builder_t *B __PLQ_plq_message_t_formal_args);
__flatbuffers_build_table_prolog(flatbuffers_, PLQ_plq_message_t, PLQ_plq_message_t_file_identifier, PLQ_plq_message_t_type_identifier)

static inline PLQ_plq_payload_t_union_ref_t PLQ_plq_payload_t_as_NONE(void)
{ PLQ_plq_payload_t_union_ref_t uref; uref.type = PLQ_plq_payload_t_NONE; uref.value = 0; return uref; }
static inline PLQ_plq_payload_t_union_ref_t PLQ_plq_payload_t_as_plq_frame_t(PLQ_plq_frame_t_ref_t ref)
{ PLQ_plq_payload_t_union_ref_t uref; uref.type = PLQ_plq_payload_t_plq_frame_t; uref.value = ref; return uref; }
static inline PLQ_plq_payload_t_union_ref_t PLQ_plq_payload_t_as_plq_mapchange_t(PLQ_plq_mapchange_t_ref_t ref)
{ PLQ_plq_payload_t_union_ref_t uref; uref.type = PLQ_plq_payload_t_plq_mapchange_t; uref.value = ref; return uref; }
static inline PLQ_plq_payload_t_union_ref_t PLQ_plq_payload_t_as_plq_lightstyles_t(PLQ_plq_lightstyles_t_ref_t ref)
{ PLQ_plq_payload_t_union_ref_t uref; uref.type = PLQ_plq_payload_t_plq_lightstyles_t; uref.value = ref; return uref; }
static inline PLQ_plq_payload_t_union_ref_t PLQ_plq_payload_t_as_plq_disconnect_t(PLQ_plq_disconnect_t_ref_t ref)
{ PLQ_plq_payload_t_union_ref_t uref; uref.type = PLQ_plq_payload_t_plq_disconnect_t; uref.value = ref; return uref; }
static inline PLQ_plq_payload_t_union_ref_t PLQ_plq_payload_t_as_plq_input_t(PLQ_plq_input_t_ref_t ref)
{ PLQ_plq_payload_t_union_ref_t uref; uref.type = PLQ_plq_payload_t_plq_input_t; uref.value = ref; return uref; }
static inline PLQ_plq_payload_t_union_ref_t PLQ_plq_payload_t_as_plq_command_t(PLQ_plq_command_t_ref_t ref)
{ PLQ_plq_payload_t_union_ref_t uref; uref.type = PLQ_plq_payload_t_plq_command_t; uref.value = ref; return uref; }
static inline PLQ_plq_payload_t_union_ref_t PLQ_plq_payload_t_as_plq_resourcereq_t(PLQ_plq_resourcereq_t_ref_t ref)
{ PLQ_plq_payload_t_union_ref_t uref; uref.type = PLQ_plq_payload_t_plq_resourcereq_t; uref.value = ref; return uref; }
static inline PLQ_plq_payload_t_union_ref_t PLQ_plq_payload_t_as_plq_resourceresp_t(PLQ_plq_resourceresp_t_ref_t ref)
{ PLQ_plq_payload_t_union_ref_t uref; uref.type = PLQ_plq_payload_t_plq_resourceresp_t; uref.value = ref; return uref; }
__flatbuffers_build_union_vector(flatbuffers_, PLQ_plq_payload_t)

static PLQ_plq_payload_t_union_ref_t PLQ_plq_payload_t_clone(flatbuffers_builder_t *B, PLQ_plq_payload_t_union_t u)
{
    switch (u.type) {
    case 1: return PLQ_plq_payload_t_as_plq_frame_t(PLQ_plq_frame_t_clone(B, (PLQ_plq_frame_t_table_t)u.value));
    case 2: return PLQ_plq_payload_t_as_plq_mapchange_t(PLQ_plq_mapchange_t_clone(B, (PLQ_plq_mapchange_t_table_t)u.value));
    case 3: return PLQ_plq_payload_t_as_plq_lightstyles_t(PLQ_plq_lightstyles_t_clone(B, (PLQ_plq_lightstyles_t_table_t)u.value));
    case 4: return PLQ_plq_payload_t_as_plq_disconnect_t(PLQ_plq_disconnect_t_clone(B, (PLQ_plq_disconnect_t_table_t)u.value));
    case 5: return PLQ_plq_payload_t_as_plq_input_t(PLQ_plq_input_t_clone(B, (PLQ_plq_input_t_table_t)u.value));
    case 6: return PLQ_plq_payload_t_as_plq_command_t(PLQ_plq_command_t_clone(B, (PLQ_plq_command_t_table_t)u.value));
    case 7: return PLQ_plq_payload_t_as_plq_resourcereq_t(PLQ_plq_resourcereq_t_clone(B, (PLQ_plq_resourcereq_t_table_t)u.value));
    case 8: return PLQ_plq_payload_t_as_plq_resourceresp_t(PLQ_plq_resourceresp_t_clone(B, (PLQ_plq_resourceresp_t_table_t)u.value));
    default: return PLQ_plq_payload_t_as_NONE();
    }
}

__flatbuffers_build_struct_field(0, flatbuffers_, PLQ_plq_frame_t_view, PLQ_plq_viewstate_t, 56, 8, PLQ_plq_frame_t)
__flatbuffers_build_struct_field(1, flatbuffers_, PLQ_plq_frame_t_stats, PLQ_plq_stats_t, 64, 4, PLQ_plq_frame_t)
__flatbuffers_build_vector_field(2, flatbuffers_, PLQ_plq_frame_t_entities, PLQ_entity_state_t, PLQ_entity_state_t_t, PLQ_plq_frame_t)
__flatbuffers_build_vector_field(3, flatbuffers_, PLQ_plq_frame_t_dlights, PLQ_dlight_t, PLQ_dlight_t_t, PLQ_plq_frame_t)
__flatbuffers_build_vector_field(4, flatbuffers_, PLQ_plq_frame_t_cshifts, PLQ_cshift_t, PLQ_cshift_t_t, PLQ_plq_frame_t)

static inline PLQ_plq_frame_t_ref_t PLQ_plq_frame_t_create(flatbuffers_builder_t *B __PLQ_plq_frame_t_formal_args)
{
    if (PLQ_plq_frame_t_start(B)
        || PLQ_plq_frame_t_view_add(B, v0)
        || PLQ_plq_frame_t_stats_add(B, v1)
        || PLQ_plq_frame_t_entities_add(B, v2)
        || PLQ_plq_frame_t_dlights_add(B, v3)
        || PLQ_plq_frame_t_cshifts_add(B, v4)) {
        return 0;
    }
    return PLQ_plq_frame_t_end(B);
}

static PLQ_plq_frame_t_ref_t PLQ_plq_frame_t_clone(flatbuffers_builder_t *B, PLQ_plq_frame_t_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PLQ_plq_frame_t_start(B)
        || PLQ_plq_frame_t_view_pick(B, t)
        || PLQ_plq_frame_t_stats_pick(B, t)
        || PLQ_plq_frame_t_entities_pick(B, t)
        || PLQ_plq_frame_t_dlights_pick(B, t)
        || PLQ_plq_frame_t_cshifts_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PLQ_plq_frame_t_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, PLQ_plq_mapchange_t_mapname, PLQ_plq_mapchange_t)
__flatbuffers_build_string_field(1, flatbuffers_, PLQ_plq_mapchange_t_levelname, PLQ_plq_mapchange_t)
__flatbuffers_build_scalar_field(2, flatbuffers_, PLQ_plq_mapchange_t_maxclients, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), PLQ_plq_mapchange_t)
__flatbuffers_build_scalar_field(3, flatbuffers_, PLQ_plq_mapchange_t_gametype, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), PLQ_plq_mapchange_t)

static inline PLQ_plq_mapchange_t_ref_t PLQ_plq_mapchange_t_create(flatbuffers_builder_t *B __PLQ_plq_mapchange_t_formal_args)
{
    if (PLQ_plq_mapchange_t_start(B)
        || PLQ_plq_mapchange_t_mapname_add(B, v0)
        || PLQ_plq_mapchange_t_levelname_add(B, v1)
        || PLQ_plq_mapchange_t_maxclients_add(B, v2)
        || PLQ_plq_mapchange_t_gametype_add(B, v3)) {
        return 0;
    }
    return PLQ_plq_mapchange_t_end(B);
}

static PLQ_plq_mapchange_t_ref_t PLQ_plq_mapchange_t_clone(flatbuffers_builder_t *B, PLQ_plq_mapchange_t_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PLQ_plq_mapchange_t_start(B)
        || PLQ_plq_mapchange_t_mapname_pick(B, t)
        || PLQ_plq_mapchange_t_levelname_pick(B, t)
        || PLQ_plq_mapchange_t_maxclients_pick(B, t)
        || PLQ_plq_mapchange_t_gametype_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PLQ_plq_mapchange_t_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PLQ_plq_lightstyle_t_index, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), PLQ_plq_lightstyle_t)
__flatbuffers_build_string_field(1, flatbuffers_, PLQ_plq_lightstyle_t_map, PLQ_plq_lightstyle_t)

static inline PLQ_plq_lightstyle_t_ref_t PLQ_plq_lightstyle_t_create(flatbuffers_builder_t *B __PLQ_plq_lightstyle_t_formal_args)
{
    if (PLQ_plq_lightstyle_t_start(B)
        || PLQ_plq_lightstyle_t_map_add(B, v1)
        || PLQ_plq_lightstyle_t_index_add(B, v0)) {
        return 0;
    }
    return PLQ_plq_lightstyle_t_end(B);
}

static PLQ_plq_lightstyle_t_ref_t PLQ_plq_lightstyle_t_clone(flatbuffers_builder_t *B, PLQ_plq_lightstyle_t_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PLQ_plq_lightstyle_t_start(B)
        || PLQ_plq_lightstyle_t_map_pick(B, t)
        || PLQ_plq_lightstyle_t_index_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PLQ_plq_lightstyle_t_end(B));
}

__flatbuffers_build_table_vector_field(0, flatbuffers_, PLQ_plq_lightstyles_t_styles, PLQ_plq_lightstyle_t, PLQ_plq_lightstyles_t)

static inline PLQ_plq_lightstyles_t_ref_t PLQ_plq_lightstyles_t_create(flatbuffers_builder_t *B __PLQ_plq_lightstyles_t_formal_args)
{
    if (PLQ_plq_lightstyles_t_start(B)
        || PLQ_plq_lightstyles_t_styles_add(B, v0)) {
        return 0;
    }
    return PLQ_plq_lightstyles_t_end(B);
}

static PLQ_plq_lightstyles_t_ref_t PLQ_plq_lightstyles_t_clone(flatbuffers_builder_t *B, PLQ_plq_lightstyles_t_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PLQ_plq_lightstyles_t_start(B)
        || PLQ_plq_lightstyles_t_styles_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PLQ_plq_lightstyles_t_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, PLQ_plq_disconnect_t_reason, PLQ_plq_disconnect_t)

static inline PLQ_plq_disconnect_t_ref_t PLQ_plq_disconnect_t_create(flatbuffers_builder_t *B __PLQ_plq_disconnect_t_formal_args)
{
    if (PLQ_plq_disconnect_t_start(B)
        || PLQ_plq_disconnect_t_reason_add(B, v0)) {
        return 0;
    }
    return PLQ_plq_disconnect_t_end(B);
}

static PLQ_plq_disconnect_t_ref_t PLQ_plq_disconnect_t_clone(flatbuffers_builder_t *B, PLQ_plq_disconnect_t_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PLQ_plq_disconnect_t_start(B)
        || PLQ_plq_disconnect_t_reason_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PLQ_plq_disconnect_t_end(B));
}

__flatbuffers_build_struct_field(0, flatbuffers_, PLQ_plq_input_t_cmd, PLQ_usercmd_t, 24, 4, PLQ_plq_input_t)
__flatbuffers_build_scalar_field(1, flatbuffers_, PLQ_plq_input_t_msec, flatbuffers_uint8, uint8_t, 1, 1, UINT8_C(0), PLQ_plq_input_t)

static inline PLQ_plq_input_t_ref_t PLQ_plq_input_t_create(flatbuffers_builder_t *B __PLQ_plq_input_t_formal_args)
{
    if (PLQ_plq_input_t_start(B)
        || PLQ_plq_input_t_cmd_add(B, v0)
        || PLQ_plq_input_t_msec_add(B, v1)) {
        return 0;
    }
    return PLQ_plq_input_t_end(B);
}

static PLQ_plq_input_t_ref_t PLQ_plq_input_t_clone(flatbuffers_builder_t *B, PLQ_plq_input_t_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PLQ_plq_input_t_start(B)
        || PLQ_plq_input_t_cmd_pick(B, t)
        || PLQ_plq_input_t_msec_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PLQ_plq_input_t_end(B));
}

__flatbuffers_build_string_field(0, flatbuffers_, PLQ_plq_command_t_text, PLQ_plq_command_t)

static inline PLQ_plq_command_t_ref_t PLQ_plq_command_t_create(flatbuffers_builder_t *B __PLQ_plq_command_t_formal_args)
{
    if (PLQ_plq_command_t_start(B)
        || PLQ_plq_command_t_text_add(B, v0)) {
        return 0;
    }
    return PLQ_plq_command_t_end(B);
}

static PLQ_plq_command_t_ref_t PLQ_plq_command_t_clone(flatbuffers_builder_t *B, PLQ_plq_command_t_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PLQ_plq_command_t_start(B)
        || PLQ_plq_command_t_text_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PLQ_plq_command_t_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PLQ_plq_resourcereq_t_type, PLQ_plq_resource_type_t, PLQ_plq_resource_type_t_enum_t, 1, 1, UINT8_C(0), PLQ_plq_resourcereq_t)
__flatbuffers_build_scalar_field(1, flatbuffers_, PLQ_plq_resourcereq_t_index, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), PLQ_plq_resourcereq_t)
__flatbuffers_build_string_field(2, flatbuffers_, PLQ_plq_resourcereq_t_name, PLQ_plq_resourcereq_t)

static inline PLQ_plq_resourcereq_t_ref_t PLQ_plq_resourcereq_t_create(flatbuffers_builder_t *B __PLQ_plq_resourcereq_t_formal_args)
{
    if (PLQ_plq_resourcereq_t_start(B)
        || PLQ_plq_resourcereq_t_name_add(B, v2)
        || PLQ_plq_resourcereq_t_index_add(B, v1)
        || PLQ_plq_resourcereq_t_type_add(B, v0)) {
        return 0;
    }
    return PLQ_plq_resourcereq_t_end(B);
}

static PLQ_plq_resourcereq_t_ref_t PLQ_plq_resourcereq_t_clone(flatbuffers_builder_t *B, PLQ_plq_resourcereq_t_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PLQ_plq_resourcereq_t_start(B)
        || PLQ_plq_resourcereq_t_name_pick(B, t)
        || PLQ_plq_resourcereq_t_index_pick(B, t)
        || PLQ_plq_resourcereq_t_type_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PLQ_plq_resourcereq_t_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PLQ_plq_resourceresp_t_type, PLQ_plq_resource_type_t, PLQ_plq_resource_type_t_enum_t, 1, 1, UINT8_C(0), PLQ_plq_resourceresp_t)
__flatbuffers_build_scalar_field(1, flatbuffers_, PLQ_plq_resourceresp_t_index, flatbuffers_uint16, uint16_t, 2, 2, UINT16_C(0), PLQ_plq_resourceresp_t)
__flatbuffers_build_string_field(2, flatbuffers_, PLQ_plq_resourceresp_t_name, PLQ_plq_resourceresp_t)
__flatbuffers_build_vector_field(3, flatbuffers_, PLQ_plq_resourceresp_t_data, flatbuffers_uint8, uint8_t, PLQ_plq_resourceresp_t)

static inline PLQ_plq_resourceresp_t_ref_t PLQ_plq_resourceresp_t_create(flatbuffers_builder_t *B __PLQ_plq_resourceresp_t_formal_args)
{
    if (PLQ_plq_resourceresp_t_start(B)
        || PLQ_plq_resourceresp_t_name_add(B, v2)
        || PLQ_plq_resourceresp_t_data_add(B, v3)
        || PLQ_plq_resourceresp_t_index_add(B, v1)
        || PLQ_plq_resourceresp_t_type_add(B, v0)) {
        return 0;
    }
    return PLQ_plq_resourceresp_t_end(B);
}

static PLQ_plq_resourceresp_t_ref_t PLQ_plq_resourceresp_t_clone(flatbuffers_builder_t *B, PLQ_plq_resourceresp_t_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PLQ_plq_resourceresp_t_start(B)
        || PLQ_plq_resourceresp_t_name_pick(B, t)
        || PLQ_plq_resourceresp_t_data_pick(B, t)
        || PLQ_plq_resourceresp_t_index_pick(B, t)
        || PLQ_plq_resourceresp_t_type_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PLQ_plq_resourceresp_t_end(B));
}

__flatbuffers_build_scalar_field(0, flatbuffers_, PLQ_plq_message_t_type, PLQ_plq_msgtype_t, PLQ_plq_msgtype_t_enum_t, 1, 1, UINT8_C(0), PLQ_plq_message_t)
__flatbuffers_build_union_field(2, flatbuffers_, PLQ_plq_message_t_payload, PLQ_plq_payload_t, PLQ_plq_message_t)
__flatbuffers_build_union_table_value_field(flatbuffers_, PLQ_plq_message_t_payload, PLQ_plq_payload_t, plq_frame_t, PLQ_plq_frame_t)
__flatbuffers_build_union_table_value_field(flatbuffers_, PLQ_plq_message_t_payload, PLQ_plq_payload_t, plq_mapchange_t, PLQ_plq_mapchange_t)
__flatbuffers_build_union_table_value_field(flatbuffers_, PLQ_plq_message_t_payload, PLQ_plq_payload_t, plq_lightstyles_t, PLQ_plq_lightstyles_t)
__flatbuffers_build_union_table_value_field(flatbuffers_, PLQ_plq_message_t_payload, PLQ_plq_payload_t, plq_disconnect_t, PLQ_plq_disconnect_t)
__flatbuffers_build_union_table_value_field(flatbuffers_, PLQ_plq_message_t_payload, PLQ_plq_payload_t, plq_input_t, PLQ_plq_input_t)
__flatbuffers_build_union_table_value_field(flatbuffers_, PLQ_plq_message_t_payload, PLQ_plq_payload_t, plq_command_t, PLQ_plq_command_t)
__flatbuffers_build_union_table_value_field(flatbuffers_, PLQ_plq_message_t_payload, PLQ_plq_payload_t, plq_resourcereq_t, PLQ_plq_resourcereq_t)
__flatbuffers_build_union_table_value_field(flatbuffers_, PLQ_plq_message_t_payload, PLQ_plq_payload_t, plq_resourceresp_t, PLQ_plq_resourceresp_t)

static inline PLQ_plq_message_t_ref_t PLQ_plq_message_t_create(flatbuffers_builder_t *B __PLQ_plq_message_t_formal_args)
{
    if (PLQ_plq_message_t_start(B)
        || PLQ_plq_message_t_payload_add_value(B, v2)
        || PLQ_plq_message_t_type_add(B, v0)
        || PLQ_plq_message_t_payload_add_type(B, v2.type)) {
        return 0;
    }
    return PLQ_plq_message_t_end(B);
}

static PLQ_plq_message_t_ref_t PLQ_plq_message_t_clone(flatbuffers_builder_t *B, PLQ_plq_message_t_table_t t)
{
    __flatbuffers_memoize_begin(B, t);
    if (PLQ_plq_message_t_start(B)
        || PLQ_plq_message_t_payload_pick(B, t)
        || PLQ_plq_message_t_type_pick(B, t)) {
        return 0;
    }
    __flatbuffers_memoize_end(B, t, PLQ_plq_message_t_end(B));
}

#include "flatcc/flatcc_epilogue.h"
#endif /* PLQ_BUILDER_H */
