#ifndef PLQ_READER_H
#define PLQ_READER_H

/* Generated by flatcc 0.6.1 FlatBuffers schema compiler for C by dvide.com */

#ifndef FLATBUFFERS_COMMON_READER_H
#include "flatbuffers_common_reader.h"
#endif
#include "flatcc/flatcc_flatbuffers.h"
#ifndef __alignas_is_defined
#include <stdalign.h>
#endif
#include "flatcc/flatcc_prologue.h"
#ifndef flatbuffers_identifier
#define flatbuffers_identifier 0
#endif
#ifndef flatbuffers_extension
#define flatbuffers_extension "bin"
#endif

typedef struct PLQ_usercmd_t PLQ_usercmd_t_t;
typedef const PLQ_usercmd_t_t *PLQ_usercmd_t_struct_t;
typedef PLQ_usercmd_t_t *PLQ_usercmd_t_mutable_struct_t;
typedef const PLQ_usercmd_t_t *PLQ_usercmd_t_vec_t;
typedef PLQ_usercmd_t_t *PLQ_usercmd_t_mutable_vec_t;
typedef struct PLQ_entity_state_t PLQ_entity_state_t_t;
typedef const PLQ_entity_state_t_t *PLQ_entity_state_t_struct_t;
typedef PLQ_entity_state_t_t *PLQ_entity_state_t_mutable_struct_t;
typedef const PLQ_entity_state_t_t *PLQ_entity_state_t_vec_t;
typedef PLQ_entity_state_t_t *PLQ_entity_state_t_mutable_vec_t;
typedef struct PLQ_dlight_t PLQ_dlight_t_t;
typedef const PLQ_dlight_t_t *PLQ_dlight_t_struct_t;
typedef PLQ_dlight_t_t *PLQ_dlight_t_mutable_struct_t;
typedef const PLQ_dlight_t_t *PLQ_dlight_t_vec_t;
typedef PLQ_dlight_t_t *PLQ_dlight_t_mutable_vec_t;
typedef struct PLQ_cshift_t PLQ_cshift_t_t;
typedef const PLQ_cshift_t_t *PLQ_cshift_t_struct_t;
typedef PLQ_cshift_t_t *PLQ_cshift_t_mutable_struct_t;
typedef const PLQ_cshift_t_t *PLQ_cshift_t_vec_t;
typedef PLQ_cshift_t_t *PLQ_cshift_t_mutable_vec_t;
typedef struct PLQ_plq_viewstate_t PLQ_plq_viewstate_t_t;
typedef const PLQ_plq_viewstate_t_t *PLQ_plq_viewstate_t_struct_t;
typedef PLQ_plq_viewstate_t_t *PLQ_plq_viewstate_t_mutable_struct_t;
typedef const PLQ_plq_viewstate_t_t *PLQ_plq_viewstate_t_vec_t;
typedef PLQ_plq_viewstate_t_t *PLQ_plq_viewstate_t_mutable_vec_t;
typedef struct PLQ_plq_stats_t PLQ_plq_stats_t_t;
typedef const PLQ_plq_stats_t_t *PLQ_plq_stats_t_struct_t;
typedef PLQ_plq_stats_t_t *PLQ_plq_stats_t_mutable_struct_t;
typedef const PLQ_plq_stats_t_t *PLQ_plq_stats_t_vec_t;
typedef PLQ_plq_stats_t_t *PLQ_plq_stats_t_mutable_vec_t;

typedef const struct PLQ_plq_frame_t_table *PLQ_plq_frame_t_table_t;
typedef struct PLQ_plq_frame_t_table *PLQ_plq_frame_t_mutable_table_t;
typedef const flatbuffers_uoffset_t *PLQ_plq_frame_t_vec_t;
typedef flatbuffers_uoffset_t *PLQ_plq_frame_t_mutable_vec_t;
typedef const struct PLQ_plq_mapchange_t_table *PLQ_plq_mapchange_t_table_t;
typedef struct PLQ_plq_mapchange_t_table *PLQ_plq_mapchange_t_mutable_table_t;
typedef const flatbuffers_uoffset_t *PLQ_plq_mapchange_t_vec_t;
typedef flatbuffers_uoffset_t *PLQ_plq_mapchange_t_mutable_vec_t;
typedef const struct PLQ_plq_lightstyle_t_table *PLQ_plq_lightstyle_t_table_t;
typedef struct PLQ_plq_lightstyle_t_table *PLQ_plq_lightstyle_t_mutable_table_t;
typedef const flatbuffers_uoffset_t *PLQ_plq_lightstyle_t_vec_t;
typedef flatbuffers_uoffset_t *PLQ_plq_lightstyle_t_mutable_vec_t;
typedef const struct PLQ_plq_lightstyles_t_table *PLQ_plq_lightstyles_t_table_t;
typedef struct PLQ_plq_lightstyles_t_table *PLQ_plq_lightstyles_t_mutable_table_t;
typedef const flatbuffers_uoffset_t *PLQ_plq_lightstyles_t_vec_t;
typedef flatbuffers_uoffset_t *PLQ_plq_lightstyles_t_mutable_vec_t;
typedef const struct PLQ_plq_disconnect_t_table *PLQ_plq_disconnect_t_table_t;
typedef struct PLQ_plq_disconnect_t_table *PLQ_plq_disconnect_t_mutable_table_t;
typedef const flatbuffers_uoffset_t *PLQ_plq_disconnect_t_vec_t;
typedef flatbuffers_uoffset_t *PLQ_plq_disconnect_t_mutable_vec_t;
typedef const struct PLQ_plq_input_t_table *PLQ_plq_input_t_table_t;
typedef struct PLQ_plq_input_t_table *PLQ_plq_input_t_mutable_table_t;
typedef const flatbuffers_uoffset_t *PLQ_plq_input_t_vec_t;
typedef flatbuffers_uoffset_t *PLQ_plq_input_t_mutable_vec_t;
typedef const struct PLQ_plq_command_t_table *PLQ_plq_command_t_table_t;
typedef struct PLQ_plq_command_t_table *PLQ_plq_command_t_mutable_table_t;
typedef const flatbuffers_uoffset_t *PLQ_plq_command_t_vec_t;
typedef flatbuffers_uoffset_t *PLQ_plq_command_t_mutable_vec_t;
typedef const struct PLQ_plq_resourcereq_t_table *PLQ_plq_resourcereq_t_table_t;
typedef struct PLQ_plq_resourcereq_t_table *PLQ_plq_resourcereq_t_mutable_table_t;
typedef const flatbuffers_uoffset_t *PLQ_plq_resourcereq_t_vec_t;
typedef flatbuffers_uoffset_t *PLQ_plq_resourcereq_t_mutable_vec_t;
typedef const struct PLQ_plq_resourceresp_t_table *PLQ_plq_resourceresp_t_table_t;
typedef struct PLQ_plq_resourceresp_t_table *PLQ_plq_resourceresp_t_mutable_table_t;
typedef const flatbuffers_uoffset_t *PLQ_plq_resourceresp_t_vec_t;
typedef flatbuffers_uoffset_t *PLQ_plq_resourceresp_t_mutable_vec_t;
typedef const struct PLQ_plq_message_t_table *PLQ_plq_message_t_table_t;
typedef struct PLQ_plq_message_t_table *PLQ_plq_message_t_mutable_table_t;
typedef const flatbuffers_uoffset_t *PLQ_plq_message_t_vec_t;
typedef flatbuffers_uoffset_t *PLQ_plq_message_t_mutable_vec_t;
#ifndef PLQ_usercmd_t_file_identifier
#define PLQ_usercmd_t_file_identifier 0
#endif
/* deprecated, use PLQ_usercmd_t_file_identifier */
#ifndef PLQ_usercmd_t_identifier
#define PLQ_usercmd_t_identifier 0
#endif
#define PLQ_usercmd_t_type_hash ((flatbuffers_thash_t)0xce11ffb8)
#define PLQ_usercmd_t_type_identifier "\xb8\xff\x11\xce"
#ifndef PLQ_usercmd_t_file_extension
#define PLQ_usercmd_t_file_extension "bin"
#endif
#ifndef PLQ_entity_state_t_file_identifier
#define PLQ_entity_state_t_file_identifier 0
#endif
/* deprecated, use PLQ_entity_state_t_file_identifier */
#ifndef PLQ_entity_state_t_identifier
#define PLQ_entity_state_t_identifier 0
#endif
#define PLQ_entity_state_t_type_hash ((flatbuffers_thash_t)0x1834b7cc)
#define PLQ_entity_state_t_type_identifier "\xcc\xb7\x34\x18"
#ifndef PLQ_entity_state_t_file_extension
#define PLQ_entity_state_t_file_extension "bin"
#endif
#ifndef PLQ_dlight_t_file_identifier
#define PLQ_dlight_t_file_identifier 0
#endif
/* deprecated, use PLQ_dlight_t_file_identifier */
#ifndef PLQ_dlight_t_identifier
#define PLQ_dlight_t_identifier 0
#endif
#define PLQ_dlight_t_type_hash ((flatbuffers_thash_t)0xcc7918ed)
#define PLQ_dlight_t_type_identifier "\xed\x18\x79\xcc"
#ifndef PLQ_dlight_t_file_extension
#define PLQ_dlight_t_file_extension "bin"
#endif
#ifndef PLQ_cshift_t_file_identifier
#define PLQ_cshift_t_file_identifier 0
#endif
/* deprecated, use PLQ_cshift_t_file_identifier */
#ifndef PLQ_cshift_t_identifier
#define PLQ_cshift_t_identifier 0
#endif
#define PLQ_cshift_t_type_hash ((flatbuffers_thash_t)0xbead5c3a)
#define PLQ_cshift_t_type_identifier "\x3a\x5c\xad\xbe"
#ifndef PLQ_cshift_t_file_extension
#define PLQ_cshift_t_file_extension "bin"
#endif
#ifndef PLQ_plq_viewstate_t_file_identifier
#define PLQ_plq_viewstate_t_file_identifier 0
#endif
/* deprecated, use PLQ_plq_viewstate_t_file_identifier */
#ifndef PLQ_plq_viewstate_t_identifier
#define PLQ_plq_viewstate_t_identifier 0
#endif
#define PLQ_plq_viewstate_t_type_hash ((flatbuffers_thash_t)0x58b391f3)
#define PLQ_plq_viewstate_t_type_identifier "\xf3\x91\xb3\x58"
#ifndef PLQ_plq_viewstate_t_file_extension
#define PLQ_plq_viewstate_t_file_extension "bin"
#endif
#ifndef PLQ_plq_stats_t_file_identifier
#define PLQ_plq_stats_t_file_identifier 0
#endif
/* deprecated, use PLQ_plq_stats_t_file_identifier */
#ifndef PLQ_plq_stats_t_identifier
#define PLQ_plq_stats_t_identifier 0
#endif
#define PLQ_plq_stats_t_type_hash ((flatbuffers_thash_t)0xa45c89a6)
#define PLQ_plq_stats_t_type_identifier "\xa6\x89\x5c\xa4"
#ifndef PLQ_plq_stats_t_file_extension
#define PLQ_plq_stats_t_file_extension "bin"
#endif
#ifndef PLQ_plq_frame_t_file_identifier
#define PLQ_plq_frame_t_file_identifier 0
#endif
/* deprecated, use PLQ_plq_frame_t_file_identifier */
#ifndef PLQ_plq_frame_t_identifier
#define PLQ_plq_frame_t_identifier 0
#endif
#define PLQ_plq_frame_t_type_hash ((flatbuffers_thash_t)0xa8eb98d4)
#define PLQ_plq_frame_t_type_identifier "\xd4\x98\xeb\xa8"
#ifndef PLQ_plq_frame_t_file_extension
#define PLQ_plq_frame_t_file_extension "bin"
#endif
#ifndef PLQ_plq_mapchange_t_file_identifier
#define PLQ_plq_mapchange_t_file_identifier 0
#endif
/* deprecated, use PLQ_plq_mapchange_t_file_identifier */
#ifndef PLQ_plq_mapchange_t_identifier
#define PLQ_plq_mapchange_t_identifier 0
#endif
#define PLQ_plq_mapchange_t_type_hash ((flatbuffers_thash_t)0xc9309ad3)
#define PLQ_plq_mapchange_t_type_identifier "\xd3\x9a\x30\xc9"
#ifndef PLQ_plq_mapchange_t_file_extension
#define PLQ_plq_mapchange_t_file_extension "bin"
#endif
#ifndef PLQ_plq_lightstyle_t_file_identifier
#define PLQ_plq_lightstyle_t_file_identifier 0
#endif
/* deprecated, use PLQ_plq_lightstyle_t_file_identifier */
#ifndef PLQ_plq_lightstyle_t_identifier
#define PLQ_plq_lightstyle_t_identifier 0
#endif
#define PLQ_plq_lightstyle_t_type_hash ((flatbuffers_thash_t)0xd423d32c)
#define PLQ_plq_lightstyle_t_type_identifier "\x2c\xd3\x23\xd4"
#ifndef PLQ_plq_lightstyle_t_file_extension
#define PLQ_plq_lightstyle_t_file_extension "bin"
#endif
#ifndef PLQ_plq_lightstyles_t_file_identifier
#define PLQ_plq_lightstyles_t_file_identifier 0
#endif
/* deprecated, use PLQ_plq_lightstyles_t_file_identifier */
#ifndef PLQ_plq_lightstyles_t_identifier
#define PLQ_plq_lightstyles_t_identifier 0
#endif
#define PLQ_plq_lightstyles_t_type_hash ((flatbuffers_thash_t)0xbc17493f)
#define PLQ_plq_lightstyles_t_type_identifier "\x3f\x49\x17\xbc"
#ifndef PLQ_plq_lightstyles_t_file_extension
#define PLQ_plq_lightstyles_t_file_extension "bin"
#endif
#ifndef PLQ_plq_disconnect_t_file_identifier
#define PLQ_plq_disconnect_t_file_identifier 0
#endif
/* deprecated, use PLQ_plq_disconnect_t_file_identifier */
#ifndef PLQ_plq_disconnect_t_identifier
#define PLQ_plq_disconnect_t_identifier 0
#endif
#define PLQ_plq_disconnect_t_type_hash ((flatbuffers_thash_t)0x14492a03)
#define PLQ_plq_disconnect_t_type_identifier "\x03\x2a\x49\x14"
#ifndef PLQ_plq_disconnect_t_file_extension
#define PLQ_plq_disconnect_t_file_extension "bin"
#endif
#ifndef PLQ_plq_input_t_file_identifier
#define PLQ_plq_input_t_file_identifier 0
#endif
/* deprecated, use PLQ_plq_input_t_file_identifier */
#ifndef PLQ_plq_input_t_identifier
#define PLQ_plq_input_t_identifier 0
#endif
#define PLQ_plq_input_t_type_hash ((flatbuffers_thash_t)0x704d9841)
#define PLQ_plq_input_t_type_identifier "\x41\x98\x4d\x70"
#ifndef PLQ_plq_input_t_file_extension
#define PLQ_plq_input_t_file_extension "bin"
#endif
#ifndef PLQ_plq_command_t_file_identifier
#define PLQ_plq_command_t_file_identifier 0
#endif
/* deprecated, use PLQ_plq_command_t_file_identifier */
#ifndef PLQ_plq_command_t_identifier
#define PLQ_plq_command_t_identifier 0
#endif
#define PLQ_plq_command_t_type_hash ((flatbuffers_thash_t)0xcb169284)
#define PLQ_plq_command_t_type_identifier "\x84\x92\x16\xcb"
#ifndef PLQ_plq_command_t_file_extension
#define PLQ_plq_command_t_file_extension "bin"
#endif
#ifndef PLQ_plq_resourcereq_t_file_identifier
#define PLQ_plq_resourcereq_t_file_identifier 0
#endif
/* deprecated, use PLQ_plq_resourcereq_t_file_identifier */
#ifndef PLQ_plq_resourcereq_t_identifier
#define PLQ_plq_resourcereq_t_identifier 0
#endif
#define PLQ_plq_resourcereq_t_type_hash ((flatbuffers_thash_t)0xc87aea8d)
#define PLQ_plq_resourcereq_t_type_identifier "\x8d\xea\x7a\xc8"
#ifndef PLQ_plq_resourcereq_t_file_extension
#define PLQ_plq_resourcereq_t_file_extension "bin"
#endif
#ifndef PLQ_plq_resourceresp_t_file_identifier
#define PLQ_plq_resourceresp_t_file_identifier 0
#endif
/* deprecated, use PLQ_plq_resourceresp_t_file_identifier */
#ifndef PLQ_plq_resourceresp_t_identifier
#define PLQ_plq_resourceresp_t_identifier 0
#endif
#define PLQ_plq_resourceresp_t_type_hash ((flatbuffers_thash_t)0xad231bbb)
#define PLQ_plq_resourceresp_t_type_identifier "\xbb\x1b\x23\xad"
#ifndef PLQ_plq_resourceresp_t_file_extension
#define PLQ_plq_resourceresp_t_file_extension "bin"
#endif
#ifndef PLQ_plq_message_t_file_identifier
#define PLQ_plq_message_t_file_identifier 0
#endif
/* deprecated, use PLQ_plq_message_t_file_identifier */
#ifndef PLQ_plq_message_t_identifier
#define PLQ_plq_message_t_identifier 0
#endif
#define PLQ_plq_message_t_type_hash ((flatbuffers_thash_t)0xda41d45e)
#define PLQ_plq_message_t_type_identifier "\x5e\xd4\x41\xda"
#ifndef PLQ_plq_message_t_file_extension
#define PLQ_plq_message_t_file_extension "bin"
#endif

typedef uint8_t PLQ_plq_resource_type_t_enum_t;
__flatbuffers_define_integer_type(PLQ_plq_resource_type_t, PLQ_plq_resource_type_t_enum_t, 8)
#define PLQ_plq_resource_type_t_none ((PLQ_plq_resource_type_t_enum_t)UINT8_C(0))
#define PLQ_plq_resource_type_t_texture ((PLQ_plq_resource_type_t_enum_t)UINT8_C(1))
#define PLQ_plq_resource_type_t_model ((PLQ_plq_resource_type_t_enum_t)UINT8_C(2))
#define PLQ_plq_resource_type_t_lightmap ((PLQ_plq_resource_type_t_enum_t)UINT8_C(3))
#define PLQ_plq_resource_type_t_sound ((PLQ_plq_resource_type_t_enum_t)UINT8_C(4))

static inline const char *PLQ_plq_resource_type_t_name(PLQ_plq_resource_type_t_enum_t value)
{
    switch (value) {
    case PLQ_plq_resource_type_t_none: return "none";
    case PLQ_plq_resource_type_t_texture: return "texture";
    case PLQ_plq_resource_type_t_model: return "model";
    case PLQ_plq_resource_type_t_lightmap: return "lightmap";
    case PLQ_plq_resource_type_t_sound: return "sound";
    default: return "";
    }
}

static inline int PLQ_plq_resource_type_t_is_known_value(PLQ_plq_resource_type_t_enum_t value)
{
    switch (value) {
    case PLQ_plq_resource_type_t_none: return 1;
    case PLQ_plq_resource_type_t_texture: return 1;
    case PLQ_plq_resource_type_t_model: return 1;
    case PLQ_plq_resource_type_t_lightmap: return 1;
    case PLQ_plq_resource_type_t_sound: return 1;
    default: return 0;
    }
}

typedef uint8_t PLQ_plq_msgtype_t_enum_t;
__flatbuffers_define_integer_type(PLQ_plq_msgtype_t, PLQ_plq_msgtype_t_enum_t, 8)
#define PLQ_plq_msgtype_t_none ((PLQ_plq_msgtype_t_enum_t)UINT8_C(0))
#define PLQ_plq_msgtype_t_frame ((PLQ_plq_msgtype_t_enum_t)UINT8_C(1))
#define PLQ_plq_msgtype_t_mapchange ((PLQ_plq_msgtype_t_enum_t)UINT8_C(2))
#define PLQ_plq_msgtype_t_lightstyles ((PLQ_plq_msgtype_t_enum_t)UINT8_C(3))
#define PLQ_plq_msgtype_t_disconnect ((PLQ_plq_msgtype_t_enum_t)UINT8_C(4))
#define PLQ_plq_msgtype_t_input ((PLQ_plq_msgtype_t_enum_t)UINT8_C(5))
#define PLQ_plq_msgtype_t_command ((PLQ_plq_msgtype_t_enum_t)UINT8_C(6))
#define PLQ_plq_msgtype_t_resourcereq ((PLQ_plq_msgtype_t_enum_t)UINT8_C(7))
#define PLQ_plq_msgtype_t_resourceresp ((PLQ_plq_msgtype_t_enum_t)UINT8_C(8))

static inline const char *PLQ_plq_msgtype_t_name(PLQ_plq_msgtype_t_enum_t value)
{
    switch (value) {
    case PLQ_plq_msgtype_t_none: return "none";
    case PLQ_plq_msgtype_t_frame: return "frame";
    case PLQ_plq_msgtype_t_mapchange: return "mapchange";
    case PLQ_plq_msgtype_t_lightstyles: return "lightstyles";
    case PLQ_plq_msgtype_t_disconnect: return "disconnect";
    case PLQ_plq_msgtype_t_input: return "input";
    case PLQ_plq_msgtype_t_command: return "command";
    case PLQ_plq_msgtype_t_resourcereq: return "resourcereq";
    case PLQ_plq_msgtype_t_resourceresp: return "resourceresp";
    default: return "";
    }
}

static inline int PLQ_plq_msgtype_t_is_known_value(PLQ_plq_msgtype_t_enum_t value)
{
    switch (value) {
    case PLQ_plq_msgtype_t_none: return 1;
    case PLQ_plq_msgtype_t_frame: return 1;
    case PLQ_plq_msgtype_t_mapchange: return 1;
    case PLQ_plq_msgtype_t_lightstyles: return 1;
    case PLQ_plq_msgtype_t_disconnect: return 1;
    case PLQ_plq_msgtype_t_input: return 1;
    case PLQ_plq_msgtype_t_command: return 1;
    case PLQ_plq_msgtype_t_resourcereq: return 1;
    case PLQ_plq_msgtype_t_resourceresp: return 1;
    default: return 0;
    }
}


struct PLQ_usercmd_t {
    alignas(4) float viewangles_x;
    alignas(4) float viewangles_y;
    alignas(4) float viewangles_z;
    alignas(4) float forwardmove;
    alignas(4) float sidemove;
    alignas(4) float upmove;
};
static_assert(sizeof(PLQ_usercmd_t_t) == 24, "struct size mismatch");

static inline const PLQ_usercmd_t_t *PLQ_usercmd_t__const_ptr_add(const PLQ_usercmd_t_t *p, size_t i) { return p + i; }
static inline PLQ_usercmd_t_t *PLQ_usercmd_t__ptr_add(PLQ_usercmd_t_t *p, size_t i) { return p + i; }
static inline PLQ_usercmd_t_struct_t PLQ_usercmd_t_vec_at(PLQ_usercmd_t_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t PLQ_usercmd_t__size(void) { return 24; }
static inline size_t PLQ_usercmd_t_vec_len(PLQ_usercmd_t_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(PLQ_usercmd_t)

__flatbuffers_define_struct_scalar_field(PLQ_usercmd_t, viewangles_x, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_usercmd_t, viewangles_y, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_usercmd_t, viewangles_z, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_usercmd_t, forwardmove, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_usercmd_t, sidemove, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_usercmd_t, upmove, flatbuffers_float, float)

struct PLQ_entity_state_t {
    alignas(4) float origin_x;
    alignas(4) float origin_y;
    alignas(4) float origin_z;
    alignas(4) float angles_x;
    alignas(4) float angles_y;
    alignas(4) float angles_z;
    alignas(2) uint16_t modelindex;
    alignas(2) uint16_t frame;
    alignas(1) uint8_t colormap;
    alignas(1) uint8_t skin;
    alignas(1) uint8_t alpha;
    alignas(1) uint8_t scale;
    alignas(4) int32_t effects;
};
static_assert(sizeof(PLQ_entity_state_t_t) == 36, "struct size mismatch");

static inline const PLQ_entity_state_t_t *PLQ_entity_state_t__const_ptr_add(const PLQ_entity_state_t_t *p, size_t i) { return p + i; }
static inline PLQ_entity_state_t_t *PLQ_entity_state_t__ptr_add(PLQ_entity_state_t_t *p, size_t i) { return p + i; }
static inline PLQ_entity_state_t_struct_t PLQ_entity_state_t_vec_at(PLQ_entity_state_t_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t PLQ_entity_state_t__size(void) { return 36; }
static inline size_t PLQ_entity_state_t_vec_len(PLQ_entity_state_t_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(PLQ_entity_state_t)

__flatbuffers_define_struct_scalar_field(PLQ_entity_state_t, origin_x, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_entity_state_t, origin_y, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_entity_state_t, origin_z, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_entity_state_t, angles_x, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_entity_state_t, angles_y, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_entity_state_t, angles_z, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_entity_state_t, modelindex, flatbuffers_uint16, uint16_t)
__flatbuffers_define_struct_scalar_field(PLQ_entity_state_t, frame, flatbuffers_uint16, uint16_t)
__flatbuffers_define_struct_scalar_field(PLQ_entity_state_t, colormap, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(PLQ_entity_state_t, skin, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(PLQ_entity_state_t, alpha, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(PLQ_entity_state_t, scale, flatbuffers_uint8, uint8_t)
__flatbuffers_define_struct_scalar_field(PLQ_entity_state_t, effects, flatbuffers_int32, int32_t)

struct PLQ_dlight_t {
    alignas(4) float origin_x;
    alignas(4) float origin_y;
    alignas(4) float origin_z;
    alignas(4) float radius;
    alignas(4) float spawn;
    alignas(4) float die;
    alignas(4) float decay;
    alignas(4) float minlight;
    alignas(4) int32_t key;
    alignas(4) float color_r;
    alignas(4) float color_g;
    alignas(4) float color_b;
};
static_assert(sizeof(PLQ_dlight_t_t) == 48, "struct size mismatch");

static inline const PLQ_dlight_t_t *PLQ_dlight_t__const_ptr_add(const PLQ_dlight_t_t *p, size_t i) { return p + i; }
static inline PLQ_dlight_t_t *PLQ_dlight_t__ptr_add(PLQ_dlight_t_t *p, size_t i) { return p + i; }
static inline PLQ_dlight_t_struct_t PLQ_dlight_t_vec_at(PLQ_dlight_t_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t PLQ_dlight_t__size(void) { return 48; }
static inline size_t PLQ_dlight_t_vec_len(PLQ_dlight_t_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(PLQ_dlight_t)

__flatbuffers_define_struct_scalar_field(PLQ_dlight_t, origin_x, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_dlight_t, origin_y, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_dlight_t, origin_z, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_dlight_t, radius, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_dlight_t, spawn, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_dlight_t, die, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_dlight_t, decay, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_dlight_t, minlight, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_dlight_t, key, flatbuffers_int32, int32_t)
__flatbuffers_define_struct_scalar_field(PLQ_dlight_t, color_r, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_dlight_t, color_g, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_dlight_t, color_b, flatbuffers_float, float)

struct PLQ_cshift_t {
    alignas(4) int32_t destcolor_r;
    alignas(4) int32_t destcolor_g;
    alignas(4) int32_t destcolor_b;
    alignas(4) float percent;
};
static_assert(sizeof(PLQ_cshift_t_t) == 16, "struct size mismatch");

static inline const PLQ_cshift_t_t *PLQ_cshift_t__const_ptr_add(const PLQ_cshift_t_t *p, size_t i) { return p + i; }
static inline PLQ_cshift_t_t *PLQ_cshift_t__ptr_add(PLQ_cshift_t_t *p, size_t i) { return p + i; }
static inline PLQ_cshift_t_struct_t PLQ_cshift_t_vec_at(PLQ_cshift_t_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t PLQ_cshift_t__size(void) { return 16; }
static inline size_t PLQ_cshift_t_vec_len(PLQ_cshift_t_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(PLQ_cshift_t)

__flatbuffers_define_struct_scalar_field(PLQ_cshift_t, destcolor_r, flatbuffers_int32, int32_t)
__flatbuffers_define_struct_scalar_field(PLQ_cshift_t, destcolor_g, flatbuffers_int32, int32_t)
__flatbuffers_define_struct_scalar_field(PLQ_cshift_t, destcolor_b, flatbuffers_int32, int32_t)
__flatbuffers_define_struct_scalar_field(PLQ_cshift_t, percent, flatbuffers_float, float)

struct PLQ_plq_viewstate_t {
    alignas(8) float viewangles_x;
    alignas(4) float viewangles_y;
    alignas(4) float viewangles_z;
    alignas(4) float velocity_x;
    alignas(4) float velocity_y;
    alignas(4) float velocity_z;
    alignas(4) float punchangle_x;
    alignas(4) float punchangle_y;
    alignas(4) float punchangle_z;
    alignas(4) float viewheight;
    alignas(8) double time;
    alignas(2) int16_t viewentity;
    alignas(2) uint16_t flags;
};
static_assert(sizeof(PLQ_plq_viewstate_t_t) == 56, "struct size mismatch");

static inline const PLQ_plq_viewstate_t_t *PLQ_plq_viewstate_t__const_ptr_add(const PLQ_plq_viewstate_t_t *p, size_t i) { return p + i; }
static inline PLQ_plq_viewstate_t_t *PLQ_plq_viewstate_t__ptr_add(PLQ_plq_viewstate_t_t *p, size_t i) { return p + i; }
static inline PLQ_plq_viewstate_t_struct_t PLQ_plq_viewstate_t_vec_at(PLQ_plq_viewstate_t_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t PLQ_plq_viewstate_t__size(void) { return 56; }
static inline size_t PLQ_plq_viewstate_t_vec_len(PLQ_plq_viewstate_t_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(PLQ_plq_viewstate_t)

__flatbuffers_define_struct_scalar_field(PLQ_plq_viewstate_t, viewangles_x, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_plq_viewstate_t, viewangles_y, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_plq_viewstate_t, viewangles_z, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_plq_viewstate_t, velocity_x, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_plq_viewstate_t, velocity_y, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_plq_viewstate_t, velocity_z, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_plq_viewstate_t, punchangle_x, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_plq_viewstate_t, punchangle_y, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_plq_viewstate_t, punchangle_z, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_plq_viewstate_t, viewheight, flatbuffers_float, float)
__flatbuffers_define_struct_scalar_field(PLQ_plq_viewstate_t, time, flatbuffers_double, double)
__flatbuffers_define_struct_scalar_field(PLQ_plq_viewstate_t, viewentity, flatbuffers_int16, int16_t)
__flatbuffers_define_struct_scalar_field(PLQ_plq_viewstate_t, flags, flatbuffers_uint16, uint16_t)

struct PLQ_plq_stats_t {
    alignas(4) int32_t health;
    alignas(4) int32_t frags;
    alignas(4) int32_t weapon;
    alignas(4) int32_t ammo;
    alignas(4) int32_t armor;
    alignas(4) int32_t weaponframe;
    alignas(4) int32_t shells;
    alignas(4) int32_t nails;
    alignas(4) int32_t rockets;
    alignas(4) int32_t cells;
    alignas(4) int32_t activeweapon;
    alignas(4) int32_t totalsecrets;
    alignas(4) int32_t totalmonsters;
    alignas(4) int32_t secrets;
    alignas(4) int32_t monsters;
    alignas(4) uint32_t items;
};
static_assert(sizeof(PLQ_plq_stats_t_t) == 64, "struct size mismatch");

static inline const PLQ_plq_stats_t_t *PLQ_plq_stats_t__const_ptr_add(const PLQ_plq_stats_t_t *p, size_t i) { return p + i; }
static inline PLQ_plq_stats_t_t *PLQ_plq_stats_t__ptr_add(PLQ_plq_stats_t_t *p, size_t i) { return p + i; }
static inline PLQ_plq_stats_t_struct_t PLQ_plq_stats_t_vec_at(PLQ_plq_stats_t_vec_t vec, size_t i)
__flatbuffers_struct_vec_at(vec, i)
static inline size_t PLQ_plq_stats_t__size(void) { return 64; }
static inline size_t PLQ_plq_stats_t_vec_len(PLQ_plq_stats_t_vec_t vec)
__flatbuffers_vec_len(vec)
__flatbuffers_struct_as_root(PLQ_plq_stats_t)

__flatbuffers_define_struct_scalar_field(PLQ_plq_stats_t, health, flatbuffers_int32, int32_t)
__flatbuffers_define_struct_scalar_field(PLQ_plq_stats_t, frags, flatbuffers_int32, int32_t)
__flatbuffers_define_struct_scalar_field(PLQ_plq_stats_t, weapon, flatbuffers_int32, int32_t)
__flatbuffers_define_struct_scalar_field(PLQ_plq_stats_t, ammo, flatbuffers_int32, int32_t)
__flatbuffers_define_struct_scalar_field(PLQ_plq_stats_t, armor, flatbuffers_int32, int32_t)
__flatbuffers_define_struct_scalar_field(PLQ_plq_stats_t, weaponframe, flatbuffers_int32, int32_t)
__flatbuffers_define_struct_scalar_field(PLQ_plq_stats_t, shells, flatbuffers_int32, int32_t)
__flatbuffers_define_struct_scalar_field(PLQ_plq_stats_t, nails, flatbuffers_int32, int32_t)
__flatbuffers_define_struct_scalar_field(PLQ_plq_stats_t, rockets, flatbuffers_int32, int32_t)
__flatbuffers_define_struct_scalar_field(PLQ_plq_stats_t, cells, flatbuffers_int32, int32_t)
__flatbuffers_define_struct_scalar_field(PLQ_plq_stats_t, activeweapon, flatbuffers_int32, int32_t)
__flatbuffers_define_struct_scalar_field(PLQ_plq_stats_t, totalsecrets, flatbuffers_int32, int32_t)
__flatbuffers_define_struct_scalar_field(PLQ_plq_stats_t, totalmonsters, flatbuffers_int32, int32_t)
__flatbuffers_define_struct_scalar_field(PLQ_plq_stats_t, secrets, flatbuffers_int32, int32_t)
__flatbuffers_define_struct_scalar_field(PLQ_plq_stats_t, monsters, flatbuffers_int32, int32_t)
__flatbuffers_define_struct_scalar_field(PLQ_plq_stats_t, items, flatbuffers_uint32, uint32_t)


struct PLQ_plq_frame_t_table { uint8_t unused__; };

static inline size_t PLQ_plq_frame_t_vec_len(PLQ_plq_frame_t_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PLQ_plq_frame_t_table_t PLQ_plq_frame_t_vec_at(PLQ_plq_frame_t_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PLQ_plq_frame_t_table_t, vec, i, 0)
__flatbuffers_table_as_root(PLQ_plq_frame_t)

__flatbuffers_define_struct_field(0, PLQ_plq_frame_t, view, PLQ_plq_viewstate_t_struct_t, 0)
__flatbuffers_define_struct_field(1, PLQ_plq_frame_t, stats, PLQ_plq_stats_t_struct_t, 0)
__flatbuffers_define_vector_field(2, PLQ_plq_frame_t, entities, PLQ_entity_state_t_vec_t, 0)
__flatbuffers_define_vector_field(3, PLQ_plq_frame_t, dlights, PLQ_dlight_t_vec_t, 0)
__flatbuffers_define_vector_field(4, PLQ_plq_frame_t, cshifts, PLQ_cshift_t_vec_t, 0)

struct PLQ_plq_mapchange_t_table { uint8_t unused__; };

static inline size_t PLQ_plq_mapchange_t_vec_len(PLQ_plq_mapchange_t_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PLQ_plq_mapchange_t_table_t PLQ_plq_mapchange_t_vec_at(PLQ_plq_mapchange_t_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PLQ_plq_mapchange_t_table_t, vec, i, 0)
__flatbuffers_table_as_root(PLQ_plq_mapchange_t)

__flatbuffers_define_string_field(0, PLQ_plq_mapchange_t, mapname, 0)
__flatbuffers_define_string_field(1, PLQ_plq_mapchange_t, levelname, 0)
__flatbuffers_define_scalar_field(2, PLQ_plq_mapchange_t, maxclients, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_scalar_field(3, PLQ_plq_mapchange_t, gametype, flatbuffers_uint8, uint8_t, UINT8_C(0))

struct PLQ_plq_lightstyle_t_table { uint8_t unused__; };

static inline size_t PLQ_plq_lightstyle_t_vec_len(PLQ_plq_lightstyle_t_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PLQ_plq_lightstyle_t_table_t PLQ_plq_lightstyle_t_vec_at(PLQ_plq_lightstyle_t_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PLQ_plq_lightstyle_t_table_t, vec, i, 0)
__flatbuffers_table_as_root(PLQ_plq_lightstyle_t)

__flatbuffers_define_scalar_field(0, PLQ_plq_lightstyle_t, index, flatbuffers_uint8, uint8_t, UINT8_C(0))
__flatbuffers_define_string_field(1, PLQ_plq_lightstyle_t, map, 0)

struct PLQ_plq_lightstyles_t_table { uint8_t unused__; };

static inline size_t PLQ_plq_lightstyles_t_vec_len(PLQ_plq_lightstyles_t_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PLQ_plq_lightstyles_t_table_t PLQ_plq_lightstyles_t_vec_at(PLQ_plq_lightstyles_t_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PLQ_plq_lightstyles_t_table_t, vec, i, 0)
__flatbuffers_table_as_root(PLQ_plq_lightstyles_t)

__flatbuffers_define_vector_field(0, PLQ_plq_lightstyles_t, styles, PLQ_plq_lightstyle_t_vec_t, 0)

struct PLQ_plq_disconnect_t_table { uint8_t unused__; };

static inline size_t PLQ_plq_disconnect_t_vec_len(PLQ_plq_disconnect_t_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PLQ_plq_disconnect_t_table_t PLQ_plq_disconnect_t_vec_at(PLQ_plq_disconnect_t_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PLQ_plq_disconnect_t_table_t, vec, i, 0)
__flatbuffers_table_as_root(PLQ_plq_disconnect_t)

__flatbuffers_define_string_field(0, PLQ_plq_disconnect_t, reason, 0)

struct PLQ_plq_input_t_table { uint8_t unused__; };

static inline size_t PLQ_plq_input_t_vec_len(PLQ_plq_input_t_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PLQ_plq_input_t_table_t PLQ_plq_input_t_vec_at(PLQ_plq_input_t_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PLQ_plq_input_t_table_t, vec, i, 0)
__flatbuffers_table_as_root(PLQ_plq_input_t)

__flatbuffers_define_struct_field(0, PLQ_plq_input_t, cmd, PLQ_usercmd_t_struct_t, 0)
__flatbuffers_define_scalar_field(1, PLQ_plq_input_t, msec, flatbuffers_uint8, uint8_t, UINT8_C(0))

struct PLQ_plq_command_t_table { uint8_t unused__; };

static inline size_t PLQ_plq_command_t_vec_len(PLQ_plq_command_t_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PLQ_plq_command_t_table_t PLQ_plq_command_t_vec_at(PLQ_plq_command_t_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PLQ_plq_command_t_table_t, vec, i, 0)
__flatbuffers_table_as_root(PLQ_plq_command_t)

__flatbuffers_define_string_field(0, PLQ_plq_command_t, text, 0)

struct PLQ_plq_resourcereq_t_table { uint8_t unused__; };

static inline size_t PLQ_plq_resourcereq_t_vec_len(PLQ_plq_resourcereq_t_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PLQ_plq_resourcereq_t_table_t PLQ_plq_resourcereq_t_vec_at(PLQ_plq_resourcereq_t_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PLQ_plq_resourcereq_t_table_t, vec, i, 0)
__flatbuffers_table_as_root(PLQ_plq_resourcereq_t)

__flatbuffers_define_scalar_field(0, PLQ_plq_resourcereq_t, type, PLQ_plq_resource_type_t, PLQ_plq_resource_type_t_enum_t, UINT8_C(0))
__flatbuffers_define_scalar_field(1, PLQ_plq_resourcereq_t, index, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_string_field(2, PLQ_plq_resourcereq_t, name, 0)

struct PLQ_plq_resourceresp_t_table { uint8_t unused__; };

static inline size_t PLQ_plq_resourceresp_t_vec_len(PLQ_plq_resourceresp_t_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PLQ_plq_resourceresp_t_table_t PLQ_plq_resourceresp_t_vec_at(PLQ_plq_resourceresp_t_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PLQ_plq_resourceresp_t_table_t, vec, i, 0)
__flatbuffers_table_as_root(PLQ_plq_resourceresp_t)

__flatbuffers_define_scalar_field(0, PLQ_plq_resourceresp_t, type, PLQ_plq_resource_type_t, PLQ_plq_resource_type_t_enum_t, UINT8_C(0))
__flatbuffers_define_scalar_field(1, PLQ_plq_resourceresp_t, index, flatbuffers_uint16, uint16_t, UINT16_C(0))
__flatbuffers_define_string_field(2, PLQ_plq_resourceresp_t, name, 0)
__flatbuffers_define_vector_field(3, PLQ_plq_resourceresp_t, data, flatbuffers_uint8_vec_t, 0)
typedef uint8_t PLQ_plq_payload_t_union_type_t;
__flatbuffers_define_integer_type(PLQ_plq_payload_t, PLQ_plq_payload_t_union_type_t, 8)
__flatbuffers_define_union(flatbuffers_, PLQ_plq_payload_t)
#define PLQ_plq_payload_t_NONE ((PLQ_plq_payload_t_union_type_t)UINT8_C(0))
#define PLQ_plq_payload_t_plq_frame_t ((PLQ_plq_payload_t_union_type_t)UINT8_C(1))
#define PLQ_plq_payload_t_plq_mapchange_t ((PLQ_plq_payload_t_union_type_t)UINT8_C(2))
#define PLQ_plq_payload_t_plq_lightstyles_t ((PLQ_plq_payload_t_union_type_t)UINT8_C(3))
#define PLQ_plq_payload_t_plq_disconnect_t ((PLQ_plq_payload_t_union_type_t)UINT8_C(4))
#define PLQ_plq_payload_t_plq_input_t ((PLQ_plq_payload_t_union_type_t)UINT8_C(5))
#define PLQ_plq_payload_t_plq_command_t ((PLQ_plq_payload_t_union_type_t)UINT8_C(6))
#define PLQ_plq_payload_t_plq_resourcereq_t ((PLQ_plq_payload_t_union_type_t)UINT8_C(7))
#define PLQ_plq_payload_t_plq_resourceresp_t ((PLQ_plq_payload_t_union_type_t)UINT8_C(8))

static inline const char *PLQ_plq_payload_t_type_name(PLQ_plq_payload_t_union_type_t type)
{
    switch (type) {
    case PLQ_plq_payload_t_NONE: return "NONE";
    case PLQ_plq_payload_t_plq_frame_t: return "plq_frame_t";
    case PLQ_plq_payload_t_plq_mapchange_t: return "plq_mapchange_t";
    case PLQ_plq_payload_t_plq_lightstyles_t: return "plq_lightstyles_t";
    case PLQ_plq_payload_t_plq_disconnect_t: return "plq_disconnect_t";
    case PLQ_plq_payload_t_plq_input_t: return "plq_input_t";
    case PLQ_plq_payload_t_plq_command_t: return "plq_command_t";
    case PLQ_plq_payload_t_plq_resourcereq_t: return "plq_resourcereq_t";
    case PLQ_plq_payload_t_plq_resourceresp_t: return "plq_resourceresp_t";
    default: return "";
    }
}

static inline int PLQ_plq_payload_t_is_known_type(PLQ_plq_payload_t_union_type_t type)
{
    switch (type) {
    case PLQ_plq_payload_t_NONE: return 1;
    case PLQ_plq_payload_t_plq_frame_t: return 1;
    case PLQ_plq_payload_t_plq_mapchange_t: return 1;
    case PLQ_plq_payload_t_plq_lightstyles_t: return 1;
    case PLQ_plq_payload_t_plq_disconnect_t: return 1;
    case PLQ_plq_payload_t_plq_input_t: return 1;
    case PLQ_plq_payload_t_plq_command_t: return 1;
    case PLQ_plq_payload_t_plq_resourcereq_t: return 1;
    case PLQ_plq_payload_t_plq_resourceresp_t: return 1;
    default: return 0;
    }
}


struct PLQ_plq_message_t_table { uint8_t unused__; };

static inline size_t PLQ_plq_message_t_vec_len(PLQ_plq_message_t_vec_t vec)
__flatbuffers_vec_len(vec)
static inline PLQ_plq_message_t_table_t PLQ_plq_message_t_vec_at(PLQ_plq_message_t_vec_t vec, size_t i)
__flatbuffers_offset_vec_at(PLQ_plq_message_t_table_t, vec, i, 0)
__flatbuffers_table_as_root(PLQ_plq_message_t)

__flatbuffers_define_scalar_field(0, PLQ_plq_message_t, type, PLQ_plq_msgtype_t, PLQ_plq_msgtype_t_enum_t, UINT8_C(0))
__flatbuffers_define_union_field(flatbuffers_, 2, PLQ_plq_message_t, payload, PLQ_plq_payload_t, 0)


#include "flatcc/flatcc_epilogue.h"
#endif /* PLQ_READER_H */
